Avoid some echo '...\...' gotchas
Problem with AC_SUBST_FILE reported by Dylan Palauzov in:
https://lists.gnu.org/r/bug-autoconf/2024-10/msg00018.html
The other problems I found by a manual scan.
* bootstrap: Use printf, not echo.
* doc/autoconf.texi (Polymorphic Variables):
* lib/autoconf/fortran.m4 (_AC_PROG_FC_V_OUTPUT):
* lib/autoconf/general.m4 (_AC_CANONICAL_SPLIT):
* lib/autoconf/status.m4 (_AC_SUBST_FILES):
* lib/autotest/general.m4 (AT_FINISH):
Use AS_ECHO, not echo.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -158,19 +158,22 @@ PACKAGE_BUGREPORT=$(sed -n < configure.ac \
    -e 's/^m4_define(\[autoconf_PACKAGE_BUGREPORT], \[\([^]]*\)])$/\1/p')
 
 if [ -z "$RELEASE_YEAR" ]; then
-    echo "$me: error: could not extract RELEASE_YEAR from configure.ac" >&2
+    printf >&2 '%s\n' \
+      "$me: error: could not extract RELEASE_YEAR from configure.ac"
     exit 1
 fi
 if [ -z "$VERSION" ]; then
-    echo "$me: error: could not compute VERSION" >&2
+    printf >&2 '%s\n' "$me: error: could not compute VERSION"
     exit 1
 fi
 if [ -z "$PACKAGE_NAME" ]; then
-    echo "$me: error: could not extract PACKAGE_NAME from configure.ac" >&2
+    printf >&2 '%s\n' \
+      "$me: error: could not extract PACKAGE_NAME from configure.ac"
     exit 1
 fi
 if [ -z "$PACKAGE_BUGREPORT" ]; then
-    echo "$me: error: could not extract PACKAGE_BUGREPORT from configure.ac" >&2
+    printf >&2 '%s\n' \
+      "$me: error: could not extract PACKAGE_BUGREPORT from configure.ac"
     exit 1
 fi
 
