* configure.ac (AT_CONFIG): Fix the path. * m4/atconfig.m4 (AT_CONFIG): Don't use EOF but ATEOF so that 2.52 can be used.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1125,11 +1125,16 @@ AUTOHEADER=${AUTOHEADER-"${am_missing_run}autoheader"}
 MAKEINFO=${MAKEINFO-"${am_missing_run}makeinfo"}
 
 # Initialize the test suite.
-AUTOTEST_PATH=../bin
+ac_config_commands="$ac_config_commands tests/atconfig"
+
+if test -f $srcdir/tests/atlocal.in; then
+  ac_config_files="$ac_config_files tests/atlocal"
+
+fi
 
 # Extract the first word of "expr", so it can be a program name with args.
 set dummy expr; ac_word=$2
-echo "$as_me:1132: checking for $ac_word" >&5
+echo "$as_me:1137: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_EXPR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1146,7 +1151,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_EXPR="$ac_dir/$ac_word"
-   echo "$as_me:1149: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1154: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1157,10 +1162,10 @@ fi
 EXPR=$ac_cv_path_EXPR
 
 if test -n "$EXPR"; then
-  echo "$as_me:1160: result: $EXPR" >&5
+  echo "$as_me:1165: result: $EXPR" >&5
 echo "${ECHO_T}$EXPR" >&6
 else
-  echo "$as_me:1163: result: no" >&5
+  echo "$as_me:1168: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1172,7 +1177,7 @@ for ac_prog in gm4 gnum4 m4
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1175: checking for $ac_word" >&5
+echo "$as_me:1180: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1189,7 +1194,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_M4="$ac_dir/$ac_word"
-   echo "$as_me:1192: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1197: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1200,10 +1205,10 @@ fi
 M4=$ac_cv_path_M4
 
 if test -n "$M4"; then
-  echo "$as_me:1203: result: $M4" >&5
+  echo "$as_me:1208: result: $M4" >&5
 echo "${ECHO_T}$M4" >&6
 else
-  echo "$as_me:1206: result: no" >&5
+  echo "$as_me:1211: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1211,7 +1216,7 @@ fi
 done
 test -n "$M4" || M4="m4"
 
-echo "$as_me:1214: checking whether m4 supports frozen files" >&5
+echo "$as_me:1219: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1223,10 +1228,10 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "$as_me:1226: result: $ac_cv_prog_gnu_m4" >&5
+echo "$as_me:1231: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { { echo "$as_me:1229: error: GNU M4 1.4 is required" >&5
+  { { echo "$as_me:1234: error: GNU M4 1.4 is required" >&5
 echo "$as_me: error: GNU M4 1.4 is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1238,7 +1243,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1241: checking for $ac_word" >&5
+echo "$as_me:1246: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1253,7 +1258,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_AWK="$ac_prog"
-echo "$as_me:1256: found $ac_dir/$ac_word" >&5
+echo "$as_me:1261: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1261,10 +1266,10 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1264: result: $AWK" >&5
+  echo "$as_me:1269: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1267: result: no" >&5
+  echo "$as_me:1272: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1278,7 +1283,7 @@ HELP2MAN=${HELP2MAN-"${am_missing_run}help2man"}
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1281: checking for $ac_word" >&5
+echo "$as_me:1286: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1295,7 +1300,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PERL="$ac_dir/$ac_word"
-   echo "$as_me:1298: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1303: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1307,20 +1312,20 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1310: result: $PERL" >&5
+  echo "$as_me:1315: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1313: result: no" >&5
+  echo "$as_me:1318: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" = no; then
-  { { echo "$as_me:1318: error: perl is not found" >&5
+  { { echo "$as_me:1323: error: perl is not found" >&5
 echo "$as_me: error: perl is not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 $PERL -e 'require 5.005;' || {
-   { { echo "$as_me:1323: error: Perl 5.005 or better is required" >&5
+   { { echo "$as_me:1328: error: Perl 5.005 or better is required" >&5
 echo "$as_me: error: Perl 5.005 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 }
@@ -1328,7 +1333,7 @@ echo "$as_me: error: Perl 5.005 or better is required" >&2;}
 # Automake can't see inner AC_SUBSTS (`aclocal' is bypassed), so we tag the
 # AC_SUBSTS here too.
 
-ac_config_files="$ac_config_files Makefile m4/Makefile man/Makefile doc/Makefile config/Makefile lib/Makefile lib/Autom4te/Makefile lib/autoscan/Makefile lib/m4sugar/Makefile lib/autoconf/Makefile lib/autotest/Makefile bin/Makefile tests/Makefile tests/atconfig"
+ac_config_files="$ac_config_files Makefile m4/Makefile man/Makefile doc/Makefile config/Makefile lib/Makefile lib/Autom4te/Makefile lib/autoscan/Makefile lib/m4sugar/Makefile lib/autoconf/Makefile lib/autotest/Makefile bin/Makefile tests/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1439,7 +1444,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1442: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1447: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1557,6 +1562,9 @@ Usage: $0 [OPTIONS] [FILE]...
 Configuration files:
 $config_files
 
+Configuration commands:
+$config_commands
+
 Report bugs to <bug-autoconf@gnu.org>."
 EOF
 
@@ -1607,7 +1615,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1610: error: ambiguous option: $1
+    { { echo "$as_me:1618: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1626,7 +1634,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1629: error: unrecognized option: $1
+  -*) { { echo "$as_me:1637: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1656,11 +1664,32 @@ on `(hostname || uname -n) 2>/dev/null | sed 1q`
 _ACEOF
 EOF
 
+cat >>$CONFIG_STATUS <<EOF
+#
+# INIT-COMMANDS section.
+#
+
+at_package='$PACKAGE_NAME'
+at_version='$PACKAGE_VERSION'
+at_bugreport='$PACKAGE_BUGREPORT'
+
+at_n='$ECHO_N'
+at_c='$ECHO_C'
+
+# Path from top_build to top_src
+at_topbuild_2_topsrc=$srcdir
+
+at_shell='$SHELL'
+at_path_separator='$PATH_SEPARATOR'
+
+EOF
+
 cat >>$CONFIG_STATUS <<\EOF
 for ac_config_target in $ac_config_targets
 do
   case "$ac_config_target" in
   # Handling of arguments.
+  "tests/atlocal" ) CONFIG_FILES="$CONFIG_FILES tests/atlocal" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "m4/Makefile" ) CONFIG_FILES="$CONFIG_FILES m4/Makefile" ;;
   "man/Makefile" ) CONFIG_FILES="$CONFIG_FILES man/Makefile" ;;
@@ -1674,8 +1703,8 @@ do
   "lib/autotest/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/autotest/Makefile" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
-  "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-  *) { { echo "$as_me:1678: error: invalid argument: $ac_config_target" >&5
+  "tests/atconfig" ) CONFIG_COMMANDS="$CONFIG_COMMANDS tests/atconfig" ;;
+  *) { { echo "$as_me:1707: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1687,6 +1716,7 @@ done
 # bizarre bug on SunOS 4.1.3.
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
+  test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
 # Create a temporary directory, and hook for its removal unless debugging.
@@ -1766,7 +1796,6 @@ s,@AUTOMAKE@,$AUTOMAKE,;t t
 s,@AUTOHEADER@,$AUTOHEADER,;t t
 s,@MAKEINFO@,$MAKEINFO,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
-s,@AUTOTEST_PATH@,$AUTOTEST_PATH,;t t
 s,@EXPR@,$EXPR,;t t
 s,@M4@,$M4,;t t
 s,@AWK@,$AWK,;t t
@@ -1886,7 +1915,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1889: creating $ac_file" >&5
+    { echo "$as_me:1918: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1904,7 +1933,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1907: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1936: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1917,7 +1946,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1920: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1949: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -1944,6 +1973,41 @@ s,@INSTALL@,$ac_INSTALL,;t t
     rm -f $tmp/out
   fi
 
+done
+EOF
+cat >>$CONFIG_STATUS <<\EOF
+
+#
+# CONFIG_COMMANDS section.
+#
+for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+
+  case $ac_dest in
+    tests/atconfig ) cat >tests/atconfig <<ATEOF
+# Configurable variable values for building test suites.
+# Generated by $0
+# Copyright 2000, 2001 Free Software Foundation, Inc.
+
+at_package='$at_package'
+at_version='$at_version'
+at_bugreport='$at_bugreport'
+
+at_n='$at_n'
+at_c='$at_c'
+
+at_testdir='tests'
+at_topbuild_2_topsrc='$at_topbuild_2_topsrc'
+
+AUTOTEST_PATH='../bin'
+
+SHELL=\${CONFIG_SHELL-'$at_shell'}
+PATH_SEPARATOR='$at_path_separator'
+
+ATEOF
+ ;;
+  esac
 done
 EOF
 
