* configure.in (standards_texi): Remove, dead code.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1438,11 +1438,6 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
-# Work with the GNU or Cygnus source tree layout.
-if test -f $srcdir/standards.texi; then
-  standards_texi=standards.texi
-fi
-
 # Automake can't see inner AC_SUBSTS (`aclocal' is bypassed), so we tag the
 # AC_SUBSTS here too.
 
@@ -1556,7 +1551,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1559: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1554: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1724,7 +1719,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1727: error: ambiguous option: $1
+    { { echo "$as_me:1722: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1752,12 +1747,12 @@ Try \`$0 --help' for more information." >&2;}
   'tests/atconfig' ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:1755: error: unrecognized option: $1
+  -*) { { echo "$as_me:1750: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:1760: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:1755: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1868,7 +1863,6 @@ s,@AWK@,$AWK,;t t
 s,@HELP2MAN@,$HELP2MAN,;t t
 s,@PERL@,$PERL,;t t
 s,@PERLSCRIPTS@,$PERLSCRIPTS,;t t
-s,@standards_texi@,$standards_texi,;t t
 CEOF
 
 EOF
@@ -1983,7 +1977,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1986: creating $ac_file" >&5
+    { echo "$as_me:1980: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2001,7 +1995,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2004: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1998: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2014,7 +2008,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2017: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2011: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
