Regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1082,6 +1082,42 @@ fi
   { echo "$as_me: error: sources are in $srcdir, but \`cd $srcdir' does not work" >&2
    { (exit 1); exit 1; }; }
 srcdir=`echo "$srcdir" | sed 's%\([^\\/]\)[\\/]*$%\1%'`
+
+ac_pwd=`pwd` && test -n "$ac_pwd" ||
+  { echo "$as_me: error: Working directory cannot be determined" >&2
+   { (exit 1); exit 1; }; }
+
+ac_pat="[\$][{][_$as_cr_Letters][_$as_cr_alnum]*[}]"
+
+for ac_dir in "$ac_pwd" "$srcdir" \
+  "$bindir" "$sbindir" "$libexecdir" "$datarootdir" "$datadir" \
+  "$sysconfdir" "$sharedstatedir" "$localstatedir" "$includedir" \
+  "$oldincludedir" "$docdir" "$infodir" "$htmldir" "$dvidir" "$pdfdir" \
+  "$psdir" "$libdir" "$localedir" "$mandir"
+do
+  # Remove references to shell or make variables.
+  ac_dirx=$ac_dir
+  while :
+  do
+    case $ac_dirx in
+    *\${*}*)
+      ac_dirx=`
+	expr "X$ac_dirx" : "X\\(.*\\)$ac_pat"`X`
+	expr "X$ac_dirx" : "X.*$ac_pat\\(.*\\)"`;;
+    *) break;;
+    esac
+  done
+
+  # Check for newline, tab, space, and other weird possibilities.
+  # Preserve that tab character below!
+  case $ac_dirx in
+  '' | -* | */-* | *'
+'* | *'	'* | *' '* | *\"* | *\#* | *\ | *\&* | *\'* | *\(* | *\)* | \
+  *\** | *\;* | *\<* | *\=* | *\>* | *\?* | *\[* | *\\* | *\`* | \
+  *\|* | \~*)
+    echo "$as_me: WARNING: Directory name \`$ac_dir' contains special characters" >&2;;
+  esac
+done
 ac_env_build_alias_set=${build_alias+set}
 ac_env_build_alias_value=$build_alias
 ac_cv_env_build_alias_set=${build_alias+set}
@@ -1203,7 +1239,6 @@ fi
 
 if test "$ac_init_help" = "recursive"; then
   # If there are subdirs, report their specific --help.
-  ac_popdir=`pwd`
   for ac_dir in : $ac_subdirs_all; do test "x$ac_dir" = x: && continue
     test -d $ac_dir || continue
     ac_builddir=.
@@ -1234,13 +1269,13 @@ esac
 
 # Do not use `cd foo && pwd` to compute absolute names, because
 # the directories may not exist.
-case `pwd` in
+case $ac_pwd in
 .) ac_abs_builddir="$ac_dir";;
 *)
   case "$ac_dir" in
-  .) ac_abs_builddir=`pwd`;;
+  .) ac_abs_builddir=$ac_pwd;;
   [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
-  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  *) ac_abs_builddir=$ac_pwd/"$ac_dir";;
   esac;;
 esac
 case $ac_abs_builddir in
@@ -1286,7 +1321,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi || ac_status=$?
-    cd "$ac_popdir" || { ac_status=$?; break; }
+    cd "$ac_pwd" || { ac_status=$?; break; }
   done
 fi
 
@@ -1648,6 +1683,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 ac_aux_dir=
 for ac_dir in config $srcdir/config; do
   if test -f $ac_dir/install-sh; then
@@ -1802,10 +1838,10 @@ fi
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 test "$program_prefix" != NONE &&
-  program_transform_name="s,^,$program_prefix,;$program_transform_name"
+  program_transform_name="s|^|$program_prefix|;$program_transform_name"
 # Use a double $ so make ignores it.
 test "$program_suffix" != NONE &&
-  program_transform_name="s,\$,$program_suffix,;$program_transform_name"
+  program_transform_name="s|\$|$program_suffix|;$program_transform_name"
 # Double any \ or $.  echo might interpret backslashes.
 # By default was `s,x,x', remove it if useless.
 cat <<\_ACEOF >conftest.sed
@@ -3075,7 +3111,8 @@ configured by $0, generated by GNU Autoconf 2.59c,
 Copyright (C) 2005 Free Software Foundation, Inc.
 This config.status script is free software; the Free Software Foundation
 gives unlimited permission to copy, distribute and modify it."
-srcdir=$srcdir
+ac_pwd='$ac_pwd'
+srcdir='$srcdir'
 INSTALL="$INSTALL"
 _ACEOF
 
@@ -3433,13 +3470,13 @@ esac
 
 # Do not use `cd foo && pwd` to compute absolute names, because
 # the directories may not exist.
-case `pwd` in
+case $ac_pwd in
 .) ac_abs_builddir="$ac_dir";;
 *)
   case "$ac_dir" in
-  .) ac_abs_builddir=`pwd`;;
+  .) ac_abs_builddir=$ac_pwd;;
   [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
-  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  *) ac_abs_builddir=$ac_pwd/"$ac_dir";;
   esac;;
 esac
 case $ac_abs_builddir in
@@ -3527,15 +3564,15 @@ _ACEOF
 cat >>$CONFIG_STATUS <<\_ACEOF
 :t
 /@[a-zA-Z_][a-zA-Z_0-9]*@/!b
-s,@configure_input@,$configure_input,;t t
-s,@srcdir@,$ac_srcdir,;t t
-s,@abs_srcdir@,$ac_abs_srcdir,;t t
-s,@top_srcdir@,$ac_top_srcdir,;t t
-s,@abs_top_srcdir@,$ac_abs_top_srcdir,;t t
-s,@builddir@,$ac_builddir,;t t
-s,@abs_builddir@,$ac_abs_builddir,;t t
-s,@top_builddir@,$ac_top_builddir,;t t
-s,@abs_top_builddir@,$ac_abs_top_builddir,;t t
+s|@configure_input@|$configure_input|;t t
+s|@srcdir@|$ac_srcdir|;t t
+s|@abs_srcdir@|$ac_abs_srcdir|;t t
+s|@top_srcdir@|$ac_top_srcdir|;t t
+s|@abs_top_srcdir@|$ac_abs_top_srcdir|;t t
+s|@builddir@|$ac_builddir|;t t
+s|@abs_builddir@|$ac_abs_builddir|;t t
+s|@top_builddir@|$ac_top_builddir|;t t
+s|@abs_top_builddir@|$ac_abs_top_builddir|;t t
 s,@INSTALL@,$ac_INSTALL,;t t
 " $ac_file_inputs | (eval "$ac_sed_cmds") >"$tmp/out"
   rm -f "$tmp/stdin"
@@ -3621,13 +3658,13 @@ esac
 
 # Do not use `cd foo && pwd` to compute absolute names, because
 # the directories may not exist.
-case `pwd` in
+case $ac_pwd in
 .) ac_abs_builddir="$ac_dir";;
 *)
   case "$ac_dir" in
-  .) ac_abs_builddir=`pwd`;;
+  .) ac_abs_builddir=$ac_pwd;;
   [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
-  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  *) ac_abs_builddir=$ac_pwd/"$ac_dir";;
   esac;;
 esac
 case $ac_abs_builddir in
