1999-10-02  Akim Demaille  <akim@epita.fr>
	AC_DIR_HEADERS is hasbeen'ed.

	* acspecific.m4 (AC_DIR_HEADER): Raised from obsolete to hasbeen.

	* acspecific.m4 (AC_CHECK_HEADERS_DIRENT, AC_CHECK_HEADER_DIRENT):
 	Removed, were used only by AC_DIR_HEADER and were not documented.

	* autoheader.m4: Remove the hooks for AC_CHECK_HEADERS_DIRENT.

	* autoconf.texi (Particular Headers): Removed the documentation of
	AC_DIR_HEADER.

	* autoconf.texi (Environment Variables): Remove the very last
	traces of documentation of --env-VAR.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -904,6 +904,12 @@ cat > $CONFIG_STATUS <<EOF
 # Compiler output produced by configure, useful for debugging
 # configure, is in ./config.log if it exists.
 
+# Files that config.status was made for.
+config_files="\\
+    Makefile testsuite/Makefile"
+config_links="\\
+    :"
+
 ac_cs_usage="\\
 \\\`$CONFIG_STATUS' instantiates files from templates according to the
 current configuration.
@@ -916,11 +922,13 @@ Usage: $CONFIG_STATUS [OPTIONS] FILE...
 
 Files to instantiate:
   Configuration files:
-    Makefile testsuite/Makefile 
+\$config_files
+  Links to install:
+\$config_links
 
 Report bugs to <bug-autoconf@gnu.org>."
 
-ac_cs_version="\
+ac_cs_version="\\
 $CONFIG_STATUS generated by autoconf version 2.14.1.
 Configured on host `(hostname || uname -n) 2>/dev/null | sed 1q` by running
   $0 $ac_configure_args"
@@ -929,9 +937,6 @@ Configured on host `(hostname || uname -n) 2>/dev/null | sed 1q` by running
 ac_cs_root=cs\$\$
 ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
-
-# Files that config.status was made for.
-config_files="Makefile testsuite/Makefile" 
 
 for ac_option
 do
@@ -943,7 +948,7 @@ do
     echo "\$ac_cs_version"; exit 0 ;;
   -help | --help | --hel | --he | --h)
     echo "\$ac_cs_usage"; exit 0 ;;
-  *) # Find out the files to process
+  *) # Find out the files to process.
     for ac_file in \$config_files
     do
       case \$ac_file in
@@ -964,6 +969,16 @@ do
       esac
     done
     test -z "\$ac_option" && continue
+    for ac_file in \$config_links
+    do
+      case \$ac_file in
+        \$ac_option | \$ac_option:* )
+          CONFIG_LINKS="\$CONFIG_LINKS \$ac_file"
+          ac_option=
+          break ;;
+      esac
+    done
+    test -z "\$ac_option" && continue
     echo "$CONFIG_STATUS: invalid argument: \$ac_option"; exit 1
    ;;
   esac
@@ -975,6 +990,7 @@ cat >> $CONFIG_STATUS <<EOF
 # If there were arguments, don't assign a default value.
 if test \$# = 0; then
   : \${CONFIG_FILES="\$config_files"}
+  : \${CONFIG_LINKS="\$config_links"}
 fi
 
 # Remove all the CONFIG_FILES, and trap to remove the temp files.
@@ -1132,6 +1148,46 @@ s%@INSTALL@%$INSTALL%;t t
   mv $ac_cs_root.out $ac_file
 fi; done
 rm -f $ac_cs_root.s*
+EOF
+cat >> $CONFIG_STATUS <<\EOF
+srcdir=$ac_given_srcdir
+
+for ac_file in : $CONFIG_LINKS; do if test "x$ac_file" != x:; then
+  ac_dest=`echo "$ac_file"|sed 's%:.*%%'`
+  ac_source=`echo "$ac_file"|sed 's%[^:]*:%%'`
+
+  echo "linking $srcdir/$ac_source to $ac_dest"
+
+  if test ! -r $srcdir/$ac_source; then
+    { echo "configure: error: $srcdir/$ac_source: File not found" 1>&2; exit 1; }
+  fi
+  rm -f $ac_dest
+
+  # Make relative symlinks.
+  # Remove last slash and all that follows it.  Not all systems have dirname.
+  ac_dest_dir=`echo $ac_dest|sed 's%/[^/][^/]*$%%'`
+  if test "$ac_dest_dir" != "$ac_dest" && test "$ac_dest_dir" != .; then
+    # The dest file is in a subdirectory.
+    test ! -d "$ac_dest_dir" && mkdir "$ac_dest_dir"
+    ac_dest_dir_suffix="/`echo $ac_dest_dir|sed 's%^\./%%'`"
+    # A "../" for each directory in $ac_dest_dir_suffix.
+    ac_dots=`echo $ac_dest_dir_suffix|sed 's%/[^/]*%../%g'`
+  else
+    ac_dest_dir_suffix= ac_dots=
+  fi
+
+  case "$srcdir" in
+  [/$]*) ac_rel_source="$srcdir/$ac_source" ;;
+  *) ac_rel_source="$ac_dots$srcdir/$ac_source" ;;
+  esac
+
+  # Make a symlink if possible; otherwise try a hard link.
+  if ln -s $ac_rel_source $ac_dest 2>/dev/null ||
+     ln $srcdir/$ac_source $ac_dest; then :
+  else
+    { echo "configure: error: cannot link $ac_dest to $srcdir/$ac_source" 1>&2; exit 1; }
+  fi
+fi; done
 EOF
 
 cat >> $CONFIG_STATUS <<EOF
