Provide a macro to canonicalize a configuration name. Suggested by Ralf Corsepius.
*  acgeneral.m4 (AC_CANONICALIZE): New macro.
(_AC_CANONICAL_THING): Use it.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -61,12 +61,9 @@ ac_init_help=
 ac_init_version=false
 # The variables have the same names as the options, with
 # dashes changed to underlines.
-build=NONE
 cache_file=/dev/null
 exec_prefix=NONE
-host=NONE
 no_create=
-nonopt=NONE
 no_recursion=
 prefix=NONE
 program_prefix=NONE
@@ -75,7 +72,6 @@ program_transform_name=s,x,x,
 silent=
 site=
 srcdir=
-target=NONE
 verbose=
 x_includes=NONE
 x_libraries=NONE
@@ -380,10 +376,8 @@ Try \`configure --help' for more information." >&2; exit 1; }
     if echo "$ac_option" | grep '[^-a-zA-Z0-9.]' >/dev/null 2>&1; then
       echo "configure: warning: invalid host type: $ac_option" >&2
     fi
-    if test "x$nonopt" != xNONE; then
-      { echo "configure: error: can only configure for one host and one target at a time" >&2; exit 1; }
-    fi
-    nonopt=$ac_option
+    echo "configure: warning: you should use --build, --host, --target" >&2
+    : ${build=$ac_option} ${host=$ac_option} ${target=$ac_option}
     ;;
 
   esac
@@ -438,7 +432,7 @@ if test "$ac_init_help" = "long"; then
   cat <<EOF
 \`configure' configures Autoconf 2.14a to adapt to many kinds of systems.
 
-Usage: $0 [OPTION]... [VAR=VALUE]... [HOST]
+Usage: $0 [OPTION]... [VAR=VALUE]...
 
 To assign environment variables (e.g., CC, CFLAGS...), specify them as
 VAR=VALUE.
@@ -453,7 +447,7 @@ Configuration:
   -q, --quiet, --silent   do not print \`checking...' messages
       --cache-file=FILE   cache test results in FILE [disabled]
   -n, --no-create         do not create output files
-      --srcdir=DIR        find the sources in DIR [configure dir or ..]
+      --srcdir=DIR        find the sources in DIR [configure dir or \`..']
 
 EOF
 
@@ -486,13 +480,6 @@ Fine tuning of the installation directories:
   --mandir=DIR           man documentation [PREFIX/man]
 EOF
 
-  cat <<\EOF
-
-Host type:
-  --host=HOST        configure for HOST [guessed]
-  --build=BUILD      configure for building on BUILD [BUILD=HOST]
-  --target=TARGET    configure for TARGET [TARGET=HOST]
-EOF
   cat <<\EOF
 
 Program names:
@@ -694,7 +681,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "configure:613: checking for a BSD compatible install" >&5
+echo "configure:601: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -741,8 +728,8 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "configure:659: result: $INSTALL" >&5
-echo "$ECHO_T""$INSTALL" >&6
+echo "configure:647: result: $INSTALL" >&5
+echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
 # It thinks the first close brace ends the variable substitution.
@@ -752,7 +739,7 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
-echo "configure:666: checking whether build environment is sane" >&5
+echo "configure:654: checking whether build environment is sane" >&5
 echo $ECHO_N "checking whether build environment is sane... $ECHO_C" >&6
 # Just in case
 sleep 1
@@ -789,8 +776,8 @@ else
 Check your system clock" >&2; exit 1; }
 fi
 rm -f conftest*
-echo "configure:701: result: yes" >&5
-echo "$ECHO_T""yes" >&6
+echo "configure:689: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 if test "$program_transform_name" = s,x,x,; then
   program_transform_name=
 else
@@ -808,9 +795,9 @@ test "$program_suffix" != NONE &&
   program_transform_name="s,\$\$,${program_suffix},;$program_transform_name"
 
 # sed with no file args requires a program.
-test "$program_transform_name" = "" && program_transform_name="s,x,x,"
+test -z "$program_transform_name" && program_transform_name="s,x,x,"
 
-echo "configure:720: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:708: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
@@ -830,12 +817,12 @@ fi
 rm -f conftestmake
 fi
 if eval "test \"`echo '$ac_cv_prog_make_'${ac_make}_set`\" = yes"; then
-  echo "configure:740: result: yes" >&5
-echo "$ECHO_T""yes" >&6
+  echo "configure:728: result: yes" >&5
+echo "${ECHO_T}yes" >&6
   SET_MAKE=
 else
-  echo "configure:744: result: no" >&5
-echo "$ECHO_T""no" >&6
+  echo "configure:732: result: no" >&5
+echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
@@ -844,94 +831,91 @@ PACKAGE=autoconf
 VERSION=2.14a
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
-  { echo "configure: error: source directory already configured; run "make distclean" there first" >&2; exit 1; }
+  { echo "configure: error: source directory already configured; run \"make distclean\" there first" >&2; exit 1; }
 fi
-#
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
 EOF
-
-#
 
 cat >>confdefs.h <<EOF
 #define VERSION "$VERSION"
 EOF
 
 missing_dir=`cd $ac_aux_dir && pwd`
-echo "configure:762: checking for working aclocal" >&5
+echo "configure:748: checking for working aclocal" >&5
 echo $ECHO_N "checking for working aclocal... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (aclocal --version) < /dev/null > /dev/null 2>&1; then
    ACLOCAL=aclocal
-   echo "configure:769: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:755: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    ACLOCAL="$missing_dir/missing aclocal"
-   echo "configure:773: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:759: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:776: checking for working autoconf" >&5
+echo "configure:762: checking for working autoconf" >&5
 echo $ECHO_N "checking for working autoconf... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (autoconf --version) < /dev/null > /dev/null 2>&1; then
    AUTOCONF=autoconf
-   echo "configure:783: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:769: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    AUTOCONF="$missing_dir/missing autoconf"
-   echo "configure:787: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:773: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:790: checking for working automake" >&5
+echo "configure:776: checking for working automake" >&5
 echo $ECHO_N "checking for working automake... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (automake --version) < /dev/null > /dev/null 2>&1; then
    AUTOMAKE=automake
-   echo "configure:797: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:783: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    AUTOMAKE="$missing_dir/missing automake"
-   echo "configure:801: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:787: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:804: checking for working autoheader" >&5
+echo "configure:790: checking for working autoheader" >&5
 echo $ECHO_N "checking for working autoheader... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (autoheader --version) < /dev/null > /dev/null 2>&1; then
    AUTOHEADER=autoheader
-   echo "configure:811: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:797: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    AUTOHEADER="$missing_dir/missing autoheader"
-   echo "configure:815: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:801: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:818: checking for working makeinfo" >&5
+echo "configure:804: checking for working makeinfo" >&5
 echo $ECHO_N "checking for working makeinfo... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (makeinfo --version) < /dev/null > /dev/null 2>&1; then
    MAKEINFO=makeinfo
-   echo "configure:825: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:811: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    MAKEINFO="$missing_dir/missing makeinfo"
-   echo "configure:829: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:815: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
 AT_TESTPATH=..
@@ -940,7 +924,7 @@ for ac_prog in gm4 gnum4 m4
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "configure:837: checking for $ac_word" >&5
+echo "configure:823: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -965,18 +949,18 @@ esac
 fi
 M4=$ac_cv_path_M4
 if test -n "$M4"; then
-  echo "configure:862: result: $M4" >&5
-echo "$ECHO_T""$M4" >&6
+  echo "configure:848: result: $M4" >&5
+echo "${ECHO_T}$M4" >&6
 else
-  echo "configure:865: result: no" >&5
-echo "$ECHO_T""no" >&6
+  echo "configure:851: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 test -n "$M4" && break
 done
 test -n "$M4" || M4="m4"
 
-echo "configure:871: checking whether m4 supports frozen files" >&5
+echo "configure:857: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -988,8 +972,8 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "configure:883: result: $ac_cv_prog_gnu_m4" >&5
-echo "$ECHO_T""$ac_cv_prog_gnu_m4" >&6
+echo "configure:869: result: $ac_cv_prog_gnu_m4" >&5
+echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
   { echo "configure: error: GNU m4 1.4 is required" >&2; exit 1; }
 fi
@@ -998,7 +982,7 @@ for ac_prog in mawk gawk nawk awk
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "configure:892: checking for $ac_word" >&5
+echo "configure:878: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1023,34 +1007,34 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "configure:917: result: $AWK" >&5
-echo "$ECHO_T""$AWK" >&6
+  echo "configure:903: result: $AWK" >&5
+echo "${ECHO_T}$AWK" >&6
 else
-  echo "configure:920: result: no" >&5
-echo "$ECHO_T""no" >&6
+  echo "configure:906: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 test -n "$AWK" && break
 done
 
-echo "configure:925: checking for working help2man" >&5
+echo "configure:911: checking for working help2man" >&5
 echo $ECHO_N "checking for working help2man... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (help2man --version) < /dev/null > /dev/null 2>&1; then
    HELP2MAN=help2man
-   echo "configure:932: result: found" >&5
-echo "$ECHO_T""found" >&6
+   echo "configure:918: result: found" >&5
+echo "${ECHO_T}found" >&6
 else
    HELP2MAN="\${SHELL} \${top_srcdir}/missing help2man"
-   echo "configure:936: result: missing" >&5
-echo "$ECHO_T""missing" >&6
+   echo "configure:922: result: missing" >&5
+echo "${ECHO_T}missing" >&6
 fi
 
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "configure:941: checking for $ac_word" >&5
+echo "configure:927: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1076,11 +1060,11 @@ esac
 fi
 PERL=$ac_cv_path_PERL
 if test -n "$PERL"; then
-  echo "configure:967: result: $PERL" >&5
-echo "$ECHO_T""$PERL" >&6
+  echo "configure:953: result: $PERL" >&5
+echo "${ECHO_T}$PERL" >&6
 else
-  echo "configure:970: result: no" >&5
-echo "$ECHO_T""no" >&6
+  echo "configure:956: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" != no; then
@@ -1100,7 +1084,7 @@ fi
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "configure:989: checking for a BSD compatible install" >&5
+echo "configure:975: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1147,8 +1131,8 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "configure:1035: result: $INSTALL" >&5
-echo "$ECHO_T""$INSTALL" >&6
+echo "configure:1021: result: $INSTALL" >&5
+echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
 # It thinks the first close brace ends the variable substitution.
@@ -1467,7 +1451,7 @@ EOF
   ac_beg=1 # First line for current file.
   ac_end=$ac_max_sed_lines # Line after last line for current file.
   ac_more_lines=:
-  ac_sed_cmds=""
+  ac_sed_cmds=
   while $ac_more_lines; do
     if test $ac_beg -gt 1; then
       sed "1,${ac_beg}d; ${ac_end}q" $ac_cs_root.subs >$ac_cs_root.sfrag
