1999-11-10  Akim Demaille  <akim@epita.fr>
	Require GNU m4 1.4 (well 1.3 in fact).

	Because we are ready to handle the case where there are no frozen
	files, we *have* to pass a -I, which is dangerous in conjunction
	with the silent including of `aclocal.m4': you may include things
	that were not expected.  Since anyway handling pre 1.3 complicates
	the task, just require an m4 which supports reloading of frozen
	files.

	* acspecific.m4 (AC_PROG_GNU_M4): Check for --reload.
	* autoconf.sh: Likewise
	* autoheader.sh: Likewise.
	* configure.in: Explicitly state the m4 version you want.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -915,7 +915,7 @@ fi
 fi
 echo "$ac_t""$ac_cv_prog_gnu_m4" 1>&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { echo "configure: error: GNU m4 is required" 1>&2; exit 1; }
+  { echo "configure: error: GNU m4 1.4 is required" 1>&2; exit 1; }
 fi
 
 for ac_prog in mawk gawk nawk awk
