Regenerate for Perl 5.005_03 and LINENO patches.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -53,16 +53,13 @@ if test "${PATH_SEPARATOR+set}" != set; then
   rm -f conftest.sh
 fi
 
-as_command='
+{
   as_lineno_1=$LINENO
   as_lineno_2=$LINENO
   as_lineno_3=`(expr $as_lineno_1 + 1) 2>/dev/null`
   test "x$as_lineno_1" != "x$as_lineno_2" &&
   test "x$as_lineno_3"  = "x$as_lineno_2"
-'
-if eval "$as_command"; then
-  :
-else
+} || {
   # Find who we are.  Look in the path if we contain no path at all
   # relative or not.
   case $0 in
@@ -96,7 +93,13 @@ do
   for as_base in sh bash ksh sh5; do
 	 case $as_dir in
 	 /*)
-	   if ("$as_dir/$as_base" -c "$as_command") 2>/dev/null; then
+	   if ("$as_dir/$as_base" -c '{
+  as_lineno_1=$LINENO
+  as_lineno_2=$LINENO
+  as_lineno_3=`(expr $as_lineno_1 + 1) 2>/dev/null`
+  test "x$as_lineno_1" != "x$as_lineno_2" &&
+  test "x$as_lineno_3"  = "x$as_lineno_2"
+}') 2>/dev/null; then
 	     CONFIG_SHELL=$as_dir/$as_base
 	     export CONFIG_SHELL
 	     exec "$CONFIG_SHELL" "$0" ${1+"$@"}
@@ -126,7 +129,7 @@ done
   . ./$as_me.lineno
   # Exit status is that of the last command.
   exit
-fi
+}
 
 # Avoid depending upon Character Ranges.
 as_cr_letters='abcdefghijklmnopqrstuvwxyz'
@@ -1551,9 +1554,9 @@ if test "$PERL" = no; then
 echo "$as_me: error: perl is not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
-$PERL -e 'require 5.005;' || {
-   { { echo "$as_me:$LINENO: error: Perl 5.005 or better is required" >&5
-echo "$as_me: error: Perl 5.005 or better is required" >&2;}
+$PERL -e 'require 5.005_03;' || {
+   { { echo "$as_me:$LINENO: error: Perl 5.005_03 or better is required" >&5
+echo "$as_me: error: Perl 5.005_03 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 }
 
@@ -1802,16 +1805,13 @@ if test "${PATH_SEPARATOR+set}" != set; then
   rm -f conftest.sh
 fi
 
-as_command='
+{
   as_lineno_1=$LINENO
   as_lineno_2=$LINENO
   as_lineno_3=`(expr $as_lineno_1 + 1) 2>/dev/null`
   test "x$as_lineno_1" != "x$as_lineno_2" &&
   test "x$as_lineno_3"  = "x$as_lineno_2"
-'
-if eval "$as_command"; then
-  :
-else
+} || {
   # Find who we are.  Look in the path if we contain no path at all
   # relative or not.
   case $0 in
@@ -1846,7 +1846,13 @@ do
   for as_base in sh bash ksh sh5; do
 	 case $as_dir in
 	 /*)
-	   if ("$as_dir/$as_base" -c "$as_command") 2>/dev/null; then
+	   if ("$as_dir/$as_base" -c '{
+  as_lineno_1=$LINENO
+  as_lineno_2=$LINENO
+  as_lineno_3=`(expr $as_lineno_1 + 1) 2>/dev/null`
+  test "x$as_lineno_1" != "x$as_lineno_2" &&
+  test "x$as_lineno_3"  = "x$as_lineno_2"
+}') 2>/dev/null; then
 	     CONFIG_SHELL=$as_dir/$as_base
 	     export CONFIG_SHELL
 	     exec "$CONFIG_SHELL" "$0" ${1+"$@"}
@@ -1876,7 +1882,7 @@ done
   . ./$as_me.lineno
   # Exit status is that of the last command.
   exit
-fi
+}
 
 # Avoid depending upon Character Ranges.
 as_cr_letters='abcdefghijklmnopqrstuvwxyz'
