Version 2.50b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.50a for GNU Autoconf 2.50a.
+# Generated by Autoconf 2.50a for GNU Autoconf 2.50b.
 #
 # Report bugs to <bug-autoconf@gnu.org>.
 #
@@ -149,8 +149,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.50a'
-PACKAGE_STRING='GNU Autoconf 2.50a'
+PACKAGE_VERSION='2.50b'
+PACKAGE_STRING='GNU Autoconf 2.50b'
 PACKAGE_BUGREPORT='bug-autoconf@gnu.org'
 
 ac_prev=
@@ -547,7 +547,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.50a to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.50b to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -609,7 +609,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.50a:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.50b:";;
    esac
   cat <<\EOF
 
@@ -656,7 +656,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.50a
+GNU Autoconf configure 2.50b
 generated by GNU Autoconf 2.50a
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -671,7 +671,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.50a, which was
+It was created by GNU Autoconf $as_me 2.50b, which was
 generated by GNU Autoconf 2.50a.  Invocation command line was
 
   $ $0 $@
@@ -832,21 +832,21 @@ for ac_var in `(set) 2>&1 |
   case $ac_old_set,$ac_new_set in
     set,)
       { echo "$as_me:834: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
-echo "$as_me: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&6;}
+echo "$as_me: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,set)
       { echo "$as_me:838: error: \`$ac_var' was not set in the previous run" >&5
-echo "$as_me: error: \`$ac_var' was not set in the previous run" >&6;}
+echo "$as_me: error: \`$ac_var' was not set in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,);;
     *)
       if test "x$ac_old_val" != "x$ac_new_val"; then
         { echo "$as_me:844: error: \`$ac_var' has changed since the previous run:" >&5
-echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&6;}
+echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&2;}
         { echo "$as_me:846:   former value:  $ac_old_val" >&5
-echo "$as_me:   former value:  $ac_old_val" >&6;}
+echo "$as_me:   former value:  $ac_old_val" >&2;}
         { echo "$as_me:848:   current value: $ac_new_val" >&5
-echo "$as_me:   current value: $ac_new_val" >&6;}
+echo "$as_me:   current value: $ac_new_val" >&2;}
         ac_cache_corrupted=:
       fi;;
   esac
@@ -865,7 +865,7 @@ echo "$as_me:   current value: $ac_new_val" >&6;}
 done
 if $ac_cache_corrupted; then
   { echo "$as_me:867: error: changes in the environment can compromise the build" >&5
-echo "$as_me: error: changes in the environment can compromise the build" >&6;}
+echo "$as_me: error: changes in the environment can compromise the build" >&2;}
   { { echo "$as_me:869: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
 echo "$as_me: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&2;}
    { (exit 1); exit 1; }; }
@@ -1096,7 +1096,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.50a
+VERSION=2.50b
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1102: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1629,7 +1629,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.50a
+GNU Autoconf config.status 2.50b
 configured by $0, generated by GNU Autoconf 2.50a,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -1692,24 +1692,15 @@ Try \`$0 --help' for more information." >&2;}
     CONFIG_HEADERS="$CONFIG_HEADERS $1"
     ac_need_defaults=false;;
 
-  # Handling of arguments.
-  'Makefile' ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  'm4/Makefile' ) CONFIG_FILES="$CONFIG_FILES m4/Makefile" ;;
-  'man/Makefile' ) CONFIG_FILES="$CONFIG_FILES man/Makefile" ;;
-  'doc/Makefile' ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  'config/Makefile' ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
-  'tests/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
-  'tests/atconfig' ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-
   # This is an error.
-  -*) { { echo "$as_me:1705: error: unrecognized option: $1
+  -*) { { echo "$as_me:1696: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:1710: error: invalid argument: $1" >&5
-echo "$as_me: error: invalid argument: $1" >&2;}
-   { (exit 1); exit 1; }; };;
+
+  *) ac_config_targets="$ac_config_targets $1" ;;
+
   esac
   shift
 done
@@ -1721,7 +1712,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.50a) 2.50a, executed with
+This file was extended by $as_me (GNU Autoconf 2.50b) 2.50a, executed with
   > $ac_cs_invocation
 on `(hostname || uname -n) 2>/dev/null | sed 1q`
 
@@ -1729,6 +1720,23 @@ _ACEOF
 EOF
 
 cat >>$CONFIG_STATUS <<\EOF
+for ac_config_target in $ac_config_targets
+do
+  case "$ac_config_target" in
+  # Handling of arguments.
+  "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "m4/Makefile" ) CONFIG_FILES="$CONFIG_FILES m4/Makefile" ;;
+  "man/Makefile" ) CONFIG_FILES="$CONFIG_FILES man/Makefile" ;;
+  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
+  "config/Makefile" ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
+  "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
+  "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
+  *) { { echo "$as_me:1734: error: invalid argument: $ac_config_target" >&5
+echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
+   { (exit 1); exit 1; }; };;
+  esac
+done
+
 # If the user did not use the arguments to specify the items to instantiate,
 # then the envvar interface is used.  Set only those that are not.
 # We use the long form for the default assignment because of an extremely
@@ -1935,7 +1943,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1938: creating $ac_file" >&5
+    { echo "$as_me:1946: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1953,7 +1961,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1956: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1964: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1966,7 +1974,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1969: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1977: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2022,7 +2030,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.50a in
+case 2.50b in
   *[a-z]*)
     cat <<EOF
 
