* bin/autom4te.in (&handle_m4): `< /dev/null' so that GNU M4 1.5 doesn't neutralize SIGINT, making autoconf etc. non interruptible. * lib/autoconf/autotest.m4 (AC_CONFIG_TESTDIR): Move the package related variables into `at_package_*'. * lib/autotest/general.m4 (AT_VICTIMS): New. (AT_INIT): Adjust for stand-alone/embedded test suites. (AS_MESSAGE_LOG_FD): Define and use it. * tests/suite.at (AT_VICTIMS): Use it. * tests/tools.at (autoupdating AC_PREREQ): Don't depend upon at_version.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -721,9 +721,15 @@ hostinfo               = `(hostinfo) 2>/dev/null               || echo unknown`
 /usr/bin/oslevel       = `(/usr/bin/oslevel) 2>/dev/null       || echo unknown`
 /bin/universe          = `(/bin/universe) 2>/dev/null          || echo unknown`
 
-PATH = $PATH
-
 _ASUNAME
+
+as_save_IFS=$IFS
+IFS=:
+for as_dir in $PATH
+do
+  echo "PATH: $as_dir"
+done
+IFS=$as_save_IFS
 } >&5
 
 cat >&5 <<_ACEOF
@@ -824,7 +830,7 @@ if test -z "$CONFIG_SITE"; then
 fi
 for ac_site_file in $CONFIG_SITE; do
   if test -r "$ac_site_file"; then
-    { echo "$as_me:827: loading site script $ac_site_file" >&5
+    { echo "$as_me:833: loading site script $ac_site_file" >&5
 echo "$as_me: loading site script $ac_site_file" >&6;}
     sed 's/^/| /' "$ac_site_file" >&5
     . "$ac_site_file"
@@ -835,7 +841,7 @@ if test -r "$cache_file"; then
   # Some versions of bash will fail to source /dev/null (special
   # files actually), so we avoid doing that.
   if test -f "$cache_file"; then
-    { echo "$as_me:838: loading cache $cache_file" >&5
+    { echo "$as_me:844: loading cache $cache_file" >&5
 echo "$as_me: loading cache $cache_file" >&6;}
     case $cache_file in
       [\\/]* | ?:[\\/]* ) . $cache_file;;
@@ -843,7 +849,7 @@ echo "$as_me: loading cache $cache_file" >&6;}
     esac
   fi
 else
-  { echo "$as_me:846: creating cache $cache_file" >&5
+  { echo "$as_me:852: creating cache $cache_file" >&5
 echo "$as_me: creating cache $cache_file" >&6;}
   >$cache_file
 fi
@@ -859,21 +865,21 @@ for ac_var in `(set) 2>&1 |
   eval ac_new_val="\$ac_env_${ac_var}_value"
   case $ac_old_set,$ac_new_set in
     set,)
-      { echo "$as_me:862: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
+      { echo "$as_me:868: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,set)
-      { echo "$as_me:866: error: \`$ac_var' was not set in the previous run" >&5
+      { echo "$as_me:872: error: \`$ac_var' was not set in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was not set in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,);;
     *)
       if test "x$ac_old_val" != "x$ac_new_val"; then
-        { echo "$as_me:872: error: \`$ac_var' has changed since the previous run:" >&5
+        { echo "$as_me:878: error: \`$ac_var' has changed since the previous run:" >&5
 echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&2;}
-        { echo "$as_me:874:   former value:  $ac_old_val" >&5
+        { echo "$as_me:880:   former value:  $ac_old_val" >&5
 echo "$as_me:   former value:  $ac_old_val" >&2;}
-        { echo "$as_me:876:   current value: $ac_new_val" >&5
+        { echo "$as_me:882:   current value: $ac_new_val" >&5
 echo "$as_me:   current value: $ac_new_val" >&2;}
         ac_cache_corrupted=:
       fi;;
@@ -892,9 +898,9 @@ echo "$as_me:   current value: $ac_new_val" >&2;}
   fi
 done
 if $ac_cache_corrupted; then
-  { echo "$as_me:895: error: changes in the environment can compromise the build" >&5
+  { echo "$as_me:901: error: changes in the environment can compromise the build" >&5
 echo "$as_me: error: changes in the environment can compromise the build" >&2;}
-  { { echo "$as_me:897: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
+  { { echo "$as_me:903: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
 echo "$as_me: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -914,10 +920,10 @@ esac
 echo "#! $SHELL" >conftest.sh
 echo  "exit 0"   >>conftest.sh
 chmod +x conftest.sh
-if { (echo "$as_me:917: PATH=\".;.\"; conftest.sh") >&5
+if { (echo "$as_me:923: PATH=\".;.\"; conftest.sh") >&5
   (PATH=".;."; conftest.sh) 2>&5
   ac_status=$?
-  echo "$as_me:920: \$? = $ac_status" >&5
+  echo "$as_me:926: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   ac_path_separator=';'
 else
@@ -943,7 +949,7 @@ for ac_dir in config $srcdir/config; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:946: error: cannot find install-sh or install.sh in config $srcdir/config" >&5
+  { { echo "$as_me:952: error: cannot find install-sh or install.sh in config $srcdir/config" >&5
 echo "$as_me: error: cannot find install-sh or install.sh in config $srcdir/config" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -963,7 +969,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "$as_me:966: checking for a BSD compatible install" >&5
+echo "$as_me:972: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1012,7 +1018,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "$as_me:1015: result: $INSTALL" >&5
+echo "$as_me:1021: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -1023,7 +1029,7 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
-echo "$as_me:1026: checking whether build environment is sane" >&5
+echo "$as_me:1032: checking whether build environment is sane" >&5
 echo $ECHO_N "checking whether build environment is sane... $ECHO_C" >&6
 # Just in case
 sleep 1
@@ -1047,7 +1053,7 @@ if (
       # if, for instance, CONFIG_SHELL is bash and it inherits a
       # broken ls alias from the environment.  This has actually
       # happened.  Such a system could not be considered "sane".
-      { { echo "$as_me:1050: error: ls -t appears to fail.  Make sure there is not a broken
+      { { echo "$as_me:1056: error: ls -t appears to fail.  Make sure there is not a broken
 alias in your environment" >&5
 echo "$as_me: error: ls -t appears to fail.  Make sure there is not a broken
 alias in your environment" >&2;}
@@ -1060,13 +1066,13 @@ then
    # Ok.
    :
 else
-   { { echo "$as_me:1063: error: newly created file is older than distributed files!
+   { { echo "$as_me:1069: error: newly created file is older than distributed files!
 Check your system clock" >&5
 echo "$as_me: error: newly created file is older than distributed files!
 Check your system clock" >&2;}
    { (exit 1); exit 1; }; }
 fi
-echo "$as_me:1069: result: yes" >&5
+echo "$as_me:1075: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 test "$program_prefix" != NONE &&
   program_transform_name="s,^,$program_prefix,;$program_transform_name"
@@ -1089,7 +1095,7 @@ if eval "$MISSING --run true"; then
 else
   am_missing_run=
   am_backtick='`'
-  { echo "$as_me:1092: WARNING: ${am_backtick}missing' script is too old or missing" >&5
+  { echo "$as_me:1098: WARNING: ${am_backtick}missing' script is too old or missing" >&5
 echo "$as_me: WARNING: ${am_backtick}missing' script is too old or missing" >&2;}
 fi
 
@@ -1100,7 +1106,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1103: checking for $ac_word" >&5
+echo "$as_me:1109: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1115,7 +1121,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_AWK="$ac_prog"
-echo "$as_me:1118: found $ac_dir/$ac_word" >&5
+echo "$as_me:1124: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1123,17 +1129,17 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1126: result: $AWK" >&5
+  echo "$as_me:1132: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1129: result: no" >&5
+  echo "$as_me:1135: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
   test -n "$AWK" && break
 done
 
-echo "$as_me:1136: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "$as_me:1142: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,./+-,__p_,'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
@@ -1153,11 +1159,11 @@ fi
 rm -f conftest.make
 fi
 if eval "test \"`echo '$ac_cv_prog_make_'${ac_make}_set`\" = yes"; then
-  echo "$as_me:1156: result: yes" >&5
+  echo "$as_me:1162: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   SET_MAKE=
 else
-  echo "$as_me:1160: result: no" >&5
+  echo "$as_me:1166: result: no" >&5
 echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
@@ -1193,7 +1199,7 @@ rmdir .deps 2>/dev/null
 # test to see if srcdir already configured
 if test "`CDPATH=:; cd $srcdir && pwd`" != "`pwd`" &&
    test -f $srcdir/config.status; then
-  { { echo "$as_me:1196: error: source directory already configured; run \"make distclean\" there first" >&5
+  { { echo "$as_me:1202: error: source directory already configured; run \"make distclean\" there first" >&5
 echo "$as_me: error: source directory already configured; run \"make distclean\" there first" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1254,7 +1260,7 @@ fi
 
 # Extract the first word of "expr", so it can be a program name with args.
 set dummy expr; ac_word=$2
-echo "$as_me:1257: checking for $ac_word" >&5
+echo "$as_me:1263: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_EXPR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1271,7 +1277,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_EXPR="$ac_dir/$ac_word"
-   echo "$as_me:1274: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1280: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1282,10 +1288,10 @@ fi
 EXPR=$ac_cv_path_EXPR
 
 if test -n "$EXPR"; then
-  echo "$as_me:1285: result: $EXPR" >&5
+  echo "$as_me:1291: result: $EXPR" >&5
 echo "${ECHO_T}$EXPR" >&6
 else
-  echo "$as_me:1288: result: no" >&5
+  echo "$as_me:1294: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1297,7 +1303,7 @@ for ac_prog in gm4 gnum4 m4
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1300: checking for $ac_word" >&5
+echo "$as_me:1306: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1314,7 +1320,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_M4="$ac_dir/$ac_word"
-   echo "$as_me:1317: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1323: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1325,10 +1331,10 @@ fi
 M4=$ac_cv_path_M4
 
 if test -n "$M4"; then
-  echo "$as_me:1328: result: $M4" >&5
+  echo "$as_me:1334: result: $M4" >&5
 echo "${ECHO_T}$M4" >&6
 else
-  echo "$as_me:1331: result: no" >&5
+  echo "$as_me:1337: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1336,7 +1342,7 @@ fi
 done
 test -n "$M4" || M4="m4"
 
-echo "$as_me:1339: checking whether m4 supports frozen files" >&5
+echo "$as_me:1345: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1348,10 +1354,10 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "$as_me:1351: result: $ac_cv_prog_gnu_m4" >&5
+echo "$as_me:1357: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { { echo "$as_me:1354: error: GNU M4 1.4 is required" >&5
+  { { echo "$as_me:1360: error: GNU M4 1.4 is required" >&5
 echo "$as_me: error: GNU M4 1.4 is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1363,7 +1369,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1366: checking for $ac_word" >&5
+echo "$as_me:1372: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1378,7 +1384,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_AWK="$ac_prog"
-echo "$as_me:1381: found $ac_dir/$ac_word" >&5
+echo "$as_me:1387: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1386,10 +1392,10 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1389: result: $AWK" >&5
+  echo "$as_me:1395: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1392: result: no" >&5
+  echo "$as_me:1398: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1403,7 +1409,7 @@ HELP2MAN=${HELP2MAN-"${am_missing_run}help2man"}
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1406: checking for $ac_word" >&5
+echo "$as_me:1412: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1420,7 +1426,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PERL="$ac_dir/$ac_word"
-   echo "$as_me:1423: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1429: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1432,20 +1438,20 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1435: result: $PERL" >&5
+  echo "$as_me:1441: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1438: result: no" >&5
+  echo "$as_me:1444: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" = no; then
-  { { echo "$as_me:1443: error: perl is not found" >&5
+  { { echo "$as_me:1449: error: perl is not found" >&5
 echo "$as_me: error: perl is not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 $PERL -e 'require 5.005;' || {
-   { { echo "$as_me:1448: error: Perl 5.005 or better is required" >&5
+   { { echo "$as_me:1454: error: Perl 5.005 or better is required" >&5
 echo "$as_me: error: Perl 5.005 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 }
@@ -1564,7 +1570,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1567: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1573: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1762,7 +1768,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1765: error: ambiguous option: $1
+    { { echo "$as_me:1771: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1781,7 +1787,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1784: error: unrecognized option: $1
+  -*) { { echo "$as_me:1790: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1800,8 +1806,9 @@ cat >>$CONFIG_STATUS <<_ACEOF
 # INIT-COMMANDS section.
 #
 
-at_package='$PACKAGE_NAME'
-at_version='$PACKAGE_VERSION'
+at_package_name='$PACKAGE_NAME'
+at_package_version='$PACKAGE_VERSION'
+at_package_string='$PACKAGE_STRING'
 at_bugreport='$PACKAGE_BUGREPORT'
 
 at_n='$ECHO_N'
@@ -1832,7 +1839,7 @@ do
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_COMMANDS="$CONFIG_COMMANDS tests/atconfig" ;;
-  *) { { echo "$as_me:1835: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1842: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2020,7 +2027,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:2023: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:2030: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -2057,7 +2064,7 @@ esac
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2060: creating $ac_file" >&5
+    { echo "$as_me:2067: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2075,7 +2082,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2078: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2085: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2088,7 +2095,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2091: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2098: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2160,16 +2167,19 @@ case $srcdir in
     ac_top_srcdir=$ac_top_builddir$srcdir ;;
 esac
 
-  { echo "$as_me:2163: executing $ac_dest commands" >&5
+  { echo "$as_me:2170: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
-    tests/atconfig ) cat >tests/atconfig <<ATEOF
+    tests/atconfig ) # Do not use _ACEOF as we are being dumped into config.status via
+# an _ACEOF-heredoe.
+cat >tests/atconfig <<ATEOF
 # Configurable variable values for building test suites.
 # Generated by $0
 # Copyright 2000, 2001 Free Software Foundation, Inc.
 
-at_package='$at_package'
-at_version='$at_version'
+at_package_name='$at_package_name'
+at_package_version='$at_package_version'
+at_package_string='$at_package_string'
 at_bugreport='$at_bugreport'
 
 at_n='$at_n'
@@ -2184,7 +2194,6 @@ AUTOTEST_PATH='tests:bin'
 
 SHELL=\${CONFIG_SHELL-'$at_shell'}
 PATH_SEPARATOR='$at_path_separator'
-
 ATEOF
  ;;
   esac
