Regenerate configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -134,18 +134,16 @@ do
   -disable-* | --disable-*)
     ac_feature=`echo "$ac_option" |sed -e 's/-*disable-//'`
     # Reject names that are not valid shell variable names.
-    case $ac_feature in
-      *[^-a-zA-Z0-9_]*) { echo "configure: error: invalid feature: $ac_feature" >&2; exit 1; };;
-    esac
+    expr "x$ac_feature" : ".*[^-a-zA-Z0-9_]" >/dev/null &&
+      { echo "configure: error: invalid feature name: $ac_feature" >&2; exit 1; }
     ac_feature=`echo $ac_feature | sed 's/-/_/g'`
     eval "enable_$ac_feature=no" ;;
 
   -enable-* | --enable-*)
     ac_feature=`echo "$ac_option" | sed -e 's/-*enable-//;s/=.*//'`
     # Reject names that are not valid shell variable names.
-    case $ac_feature in
-      *[^-a-zA-Z0-9_]*) { echo "configure: error: invalid feature: $ac_feature" >&2; exit 1; };;
-    esac
+    expr "x$ac_feature" : ".*[^-a-zA-Z0-9_]" >/dev/null &&
+      { echo "configure: error: invalid feature name: $ac_feature" >&2; exit 1; }
     ac_feature=`echo $ac_feature | sed 's/-/_/g'`
     case "$ac_option" in
       *=*) ac_optarg=`echo "$ac_optarg" | sed "s/'/'\\\\\\\\''/g"`;;
@@ -327,9 +325,8 @@ do
   -with-* | --with-*)
     ac_package=`echo "$ac_option"|sed -e 's/-*with-//;s/=.*//'`
     # Reject names that are not valid shell variable names.
-    case $ac_package in
-      *[^-a-zA-Z0-9_]*) { echo "configure: error: invalid package: $ac_package" >&2; exit 1; };;
-    esac
+    expr "x$ac_package" : ".*[^-a-zA-Z0-9_]" >/dev/null &&
+      { echo "configure: error: invalid package name: $ac_package" >&2; exit 1; }
     ac_package=`echo $ac_package| sed 's/-/_/g'`
     case "$ac_option" in
       *=*) ac_optarg=`echo "$ac_optarg" | sed "s/'/'\\\\\\\\''/g"`;;
@@ -340,9 +337,8 @@ do
   -without-* | --without-*)
     ac_package=`echo "$ac_option" |sed -e 's/-*without-//'`
     # Reject names that are not valid shell variable names.
-    case $ac_package in
-      *[^-a-zA-Z0-9_]*) { echo "configure: error: invalid package: $ac_package" >&2; exit 1; };;
-    esac
+    expr "x$ac_package" : ".*[^-a-zA-Z0-9_]" >/dev/null &&
+      { echo "configure: error: invalid package name: $ac_package" >&2; exit 1; }
     ac_package=`echo $ac_package | sed 's/-/_/g'`
     eval "with_${ac_package}=no" ;;
 
@@ -371,18 +367,16 @@ Try \`configure --help' for more information." >&2; exit 1; }
   *=*)
     ac_envvar=`echo "$ac_option" | sed -e 's/=.*//'`
     # Reject names that are not valid shell variable names.
-    case $ac_envvar in
-      *[^a-zA-Z0-9_]*) { echo "configure: error: invalid variable name: $ac_envvar" >&2; exit 1; };;
-    esac
+    expr "x$ac_envvar" : ".*[^a-zA-Z0-9_]" >/dev/null &&
+      { echo "configure: error: invalid variable name: $ac_envvar" >&2; exit 1; }
     ac_optarg=`echo "$ac_optarg" | sed "s/'/'\\\\\\\\''/g"`
     eval "$ac_envvar='$ac_optarg'"
     export $ac_envvar ;;
 
   *)
-    case $ac_option in
-      *[^-a-zA-Z0-9.]*) echo "configure: WARNING: invalid host type: $ac_option" >&2;;
-    esac
     echo "configure: WARNING: you should use --build, --host, --target" >&2
+    expr "x$ac_option" : ".*[^a-zA-Z0-9.]" >/dev/null &&
+      echo "configure: WARNING: invalid host type: $ac_option" >&2
     : ${build_alias=$ac_option} ${host_alias=$ac_option} ${target_alias=$ac_option}
     ;;
 
@@ -443,7 +437,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures this package to adapt to many kinds of systems.
+\`configure' configures Autoconf 2.14a to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -504,7 +498,9 @@ EOF
 fi
 
 if test -n "$ac_init_help"; then
-
+  case "$ac_init_help" in
+     short | recursive ) echo "Configuration of Autoconf 2.14a:";;
+   esac
   cat <<\EOF
 EOF
 fi
@@ -544,6 +540,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
+configure (Autoconf 2.14a) 2.14a
 
 Copyright (C) 1992, 93, 94, 95, 96, 98, 99, 2000
 Free Software Foundation, Inc.
@@ -625,7 +622,7 @@ echo "\
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by configure  2.14a, executed with
+It was created by configure (Autoconf 2.14a) 2.14a, executed with
  > $0 $ac_configure_args
 " >&5
 
@@ -709,7 +706,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "configure:623: checking for a BSD compatible install" >&5
+echo "configure:621: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -756,7 +753,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "configure:669: result: $INSTALL" >&5
+echo "configure:667: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -767,7 +764,7 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
-echo "configure:676: checking whether build environment is sane" >&5
+echo "configure:674: checking whether build environment is sane" >&5
 echo $ECHO_N "checking whether build environment is sane... $ECHO_C" >&6
 # Just in case
 sleep 1
@@ -804,7 +801,7 @@ else
 Check your system clock" >&2; exit 1; }
 fi
 rm -f conftest*
-echo "configure:711: result: yes" >&5
+echo "configure:709: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 if test "$program_transform_name" = s,x,x,; then
   program_transform_name=
@@ -825,7 +822,7 @@ test "$program_suffix" != NONE &&
 # sed with no file args requires a program.
 test -z "$program_transform_name" && program_transform_name="s,x,x,"
 
-echo "configure:730: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:728: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
@@ -845,11 +842,11 @@ fi
 rm -f conftestmake
 fi
 if eval "test \"`echo '$ac_cv_prog_make_'${ac_make}_set`\" = yes"; then
-  echo "configure:750: result: yes" >&5
+  echo "configure:748: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   SET_MAKE=
 else
-  echo "configure:754: result: no" >&5
+  echo "configure:752: result: no" >&5
 echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
@@ -871,78 +868,78 @@ cat >>confdefs.h <<EOF
 EOF
 
 missing_dir=`cd $ac_aux_dir && pwd`
-echo "configure:770: checking for working aclocal" >&5
+echo "configure:768: checking for working aclocal" >&5
 echo $ECHO_N "checking for working aclocal... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (aclocal --version) < /dev/null > /dev/null 2>&1; then
    ACLOCAL=aclocal
-   echo "configure:777: result: found" >&5
+   echo "configure:775: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    ACLOCAL="$missing_dir/missing aclocal"
-   echo "configure:781: result: missing" >&5
+   echo "configure:779: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:784: checking for working autoconf" >&5
+echo "configure:782: checking for working autoconf" >&5
 echo $ECHO_N "checking for working autoconf... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (autoconf --version) < /dev/null > /dev/null 2>&1; then
    AUTOCONF=autoconf
-   echo "configure:791: result: found" >&5
+   echo "configure:789: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    AUTOCONF="$missing_dir/missing autoconf"
-   echo "configure:795: result: missing" >&5
+   echo "configure:793: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:798: checking for working automake" >&5
+echo "configure:796: checking for working automake" >&5
 echo $ECHO_N "checking for working automake... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (automake --version) < /dev/null > /dev/null 2>&1; then
    AUTOMAKE=automake
-   echo "configure:805: result: found" >&5
+   echo "configure:803: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    AUTOMAKE="$missing_dir/missing automake"
-   echo "configure:809: result: missing" >&5
+   echo "configure:807: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:812: checking for working autoheader" >&5
+echo "configure:810: checking for working autoheader" >&5
 echo $ECHO_N "checking for working autoheader... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (autoheader --version) < /dev/null > /dev/null 2>&1; then
    AUTOHEADER=autoheader
-   echo "configure:819: result: found" >&5
+   echo "configure:817: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    AUTOHEADER="$missing_dir/missing autoheader"
-   echo "configure:823: result: missing" >&5
+   echo "configure:821: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
-echo "configure:826: checking for working makeinfo" >&5
+echo "configure:824: checking for working makeinfo" >&5
 echo $ECHO_N "checking for working makeinfo... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (makeinfo --version) < /dev/null > /dev/null 2>&1; then
    MAKEINFO=makeinfo
-   echo "configure:833: result: found" >&5
+   echo "configure:831: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    MAKEINFO="$missing_dir/missing makeinfo"
-   echo "configure:837: result: missing" >&5
+   echo "configure:835: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
@@ -957,7 +954,7 @@ for ac_prog in gm4 gnum4 m4
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "configure:850: checking for $ac_word" >&5
+echo "configure:848: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -968,24 +965,25 @@ else
   ;;
   *)
   ac_save_IFS=$IFS; IFS=':'
-  ac_dummy="$PATH"
-  for ac_dir in $ac_dummy; do
-    test -z "$ac_dir" && ac_dir=.
-    if test -f "$ac_dir/$ac_word"; then
-      ac_cv_path_M4=$ac_dir/$ac_word
-      break
-    fi
-  done
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if test -f "$ac_dir/$ac_word"; then
+   ac_cv_path_M4=$ac_dir/$ac_word
+   break
+fi
+done
+
   ;;
 esac
 fi
 M4=$ac_cv_path_M4
 if test -n "$M4"; then
-  echo "configure:875: result: $M4" >&5
+  echo "configure:873: result: $M4" >&5
 echo "${ECHO_T}$M4" >&6
 else
-  echo "configure:878: result: no" >&5
+  echo "configure:876: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -993,7 +991,7 @@ test -n "$M4" && break
 done
 test -n "$M4" || M4="m4"
 
-echo "configure:884: checking whether m4 supports frozen files" >&5
+echo "configure:882: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1005,7 +1003,7 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "configure:896: result: $ac_cv_prog_gnu_m4" >&5
+echo "configure:894: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
   { echo "configure: error: GNU m4 1.4 is required" >&2; exit 1; }
@@ -1018,7 +1016,7 @@ for ac_prog in mawk gawk nawk awk
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "configure:908: checking for $ac_word" >&5
+echo "configure:906: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1026,27 +1024,24 @@ else
   if test -n "$AWK"; then
   ac_cv_prog_AWK="$AWK" # Let the user override the test.
 else
-  for ac_path in `ac_save_IFS=$IFS; IFS=':'
+  ac_save_IFS=$IFS; IFS=':'
 ac_dummy="$PATH"
 for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
-  if test -f $ac_dir/$ac_word; then
-    echo "$ac_dir/$ac_word"
-  fi
+  test -f $ac_dir/$ac_word || continue
+ac_cv_prog_AWK="$ac_prog"
+break
 done
-IFS=$ac_save_IFS
-`; do
-    ac_cv_prog_AWK="$ac_prog"
-    break
-  done
+
 fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "configure:933: result: $AWK" >&5
+  echo "configure:927: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "configure:936: result: no" >&5
+  echo "configure:930: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1054,25 +1049,25 @@ test -n "$AWK" && break
 done
 
 # Generating man pages.
-echo "configure:942: checking for working help2man" >&5
+echo "configure:936: checking for working help2man" >&5
 echo $ECHO_N "checking for working help2man... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (help2man --version) < /dev/null > /dev/null 2>&1; then
    HELP2MAN=help2man
-   echo "configure:949: result: found" >&5
+   echo "configure:943: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    HELP2MAN="\${SHELL} \${top_srcdir}/missing help2man"
-   echo "configure:953: result: missing" >&5
+   echo "configure:947: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "configure:959: checking for $ac_word" >&5
+echo "configure:953: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1083,25 +1078,26 @@ else
   ;;
   *)
   ac_save_IFS=$IFS; IFS=':'
-  ac_dummy="$PATH"
-  for ac_dir in $ac_dummy; do
-    test -z "$ac_dir" && ac_dir=.
-    if test -f "$ac_dir/$ac_word"; then
-      ac_cv_path_PERL=$ac_dir/$ac_word
-      break
-    fi
-  done
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if test -f "$ac_dir/$ac_word"; then
+   ac_cv_path_PERL=$ac_dir/$ac_word
+   break
+fi
+done
+
   test -z "$ac_cv_path_PERL" && ac_cv_path_PERL="no"
   ;;
 esac
 fi
 PERL=$ac_cv_path_PERL
 if test -n "$PERL"; then
-  echo "configure:985: result: $PERL" >&5
+  echo "configure:979: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "configure:988: result: no" >&5
+  echo "configure:982: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1122,7 +1118,7 @@ fi
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "configure:1007: checking for a BSD compatible install" >&5
+echo "configure:1001: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1169,7 +1165,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "configure:1053: result: $INSTALL" >&5
+echo "configure:1047: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
