* acgeneral.m4 (_AC_INIT_PARSE_ARGS): If any option waiting for a directory receives a relative path, die (bindir, sbindir, libexecdir, datadir, sysconfdir, sharedstatedir, localstatedir, libdir, includedir, oldincludedir, infodir, mandir, exec_prefix, prefix).  Fixes Autoconf 42.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -393,6 +393,19 @@ if test -n "$ac_prev"; then
   { echo "configure: error: missing argument to --\`echo $ac_prev | sed 's/_/-/g'\`" 1>&2; exit 1; }
 fi
 
+# Be sure to have absolute paths.
+for ac_var in bindir sbindir libexecdir datadir sysconfdir sharedstatedir \
+              localstatedir libdir includedir oldincludedir infodir mandir \
+              exec_prefix prefix
+do
+  eval ac_val=$`echo $ac_var`
+  case $ac_val in
+    [\\/$]* | ?:[\\/]* ) ;;
+    NONE ) ;;
+    *)  { echo "configure: error: expected an absolute path for --$ac_var: $ac_val" 1>&2; exit 1; };;
+  esac
+done
+
 # Find the source files, if location was not specified.
 if test -z "$srcdir"; then
   ac_srcdir_defaulted=yes
@@ -672,7 +685,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" 1>&6
-echo "configure:595: checking for a BSD compatible install" 1>&5
+echo "configure:607: checking for a BSD compatible install" 1>&5
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
@@ -729,7 +742,7 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 echo $ECHO_N "checking whether build environment is sane... $ECHO_C" 1>&6
-echo "configure:647: checking whether build environment is sane" 1>&5
+echo "configure:659: checking whether build environment is sane" 1>&5
 # Just in case
 sleep 1
 echo timestamp > conftestfile
@@ -786,7 +799,7 @@ test "$program_suffix" != NONE &&
 test "$program_transform_name" = "" && program_transform_name="s,x,x,"
 
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" 1>&6
-echo "configure:700: checking whether ${MAKE-make} sets \${MAKE}" 1>&5
+echo "configure:712: checking whether ${MAKE-make} sets \${MAKE}" 1>&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
@@ -833,7 +846,7 @@ EOF
 
 missing_dir=`cd $ac_aux_dir && pwd`
 echo $ECHO_N "checking for working aclocal... $ECHO_C" 1>&6
-echo "configure:740: checking for working aclocal" 1>&5
+echo "configure:752: checking for working aclocal" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -846,7 +859,7 @@ else
 fi
 
 echo $ECHO_N "checking for working autoconf... $ECHO_C" 1>&6
-echo "configure:752: checking for working autoconf" 1>&5
+echo "configure:764: checking for working autoconf" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -859,7 +872,7 @@ else
 fi
 
 echo $ECHO_N "checking for working automake... $ECHO_C" 1>&6
-echo "configure:764: checking for working automake" 1>&5
+echo "configure:776: checking for working automake" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -872,7 +885,7 @@ else
 fi
 
 echo $ECHO_N "checking for working autoheader... $ECHO_C" 1>&6
-echo "configure:776: checking for working autoheader" 1>&5
+echo "configure:788: checking for working autoheader" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -885,7 +898,7 @@ else
 fi
 
 echo $ECHO_N "checking for working makeinfo... $ECHO_C" 1>&6
-echo "configure:788: checking for working makeinfo" 1>&5
+echo "configure:800: checking for working makeinfo" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -904,7 +917,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ECHO_N "checking for $ac_word... $ECHO_C" 1>&6
-echo "configure:805: checking for $ac_word" 1>&5
+echo "configure:817: checking for $ac_word" 1>&5
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
 else
@@ -938,7 +951,7 @@ done
 test -n "$M4" || M4="m4"
 
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" 1>&6
-echo "configure:837: checking whether m4 supports frozen files" 1>&5
+echo "configure:849: checking whether m4 supports frozen files" 1>&5
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
 else
@@ -959,7 +972,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ECHO_N "checking for $ac_word... $ECHO_C" 1>&6
-echo "configure:857: checking for $ac_word" 1>&5
+echo "configure:869: checking for $ac_word" 1>&5
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
 else
@@ -992,7 +1005,7 @@ test -n "$AWK" && break
 done
 
 echo $ECHO_N "checking for working help2man... $ECHO_C" 1>&6
-echo "configure:888: checking for working help2man" 1>&5
+echo "configure:900: checking for working help2man" 1>&5
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
@@ -1007,7 +1020,7 @@ fi
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 echo $ECHO_N "checking for $ac_word... $ECHO_C" 1>&6
-echo "configure:902: checking for $ac_word" 1>&5
+echo "configure:914: checking for $ac_word" 1>&5
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
 else
@@ -1055,7 +1068,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" 1>&6
-echo "configure:948: checking for a BSD compatible install" 1>&5
+echo "configure:960: checking for a BSD compatible install" 1>&5
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" 1>&6
