Typos.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.49d for GNU Autoconf 2.49d.
+# Generated by Autoconf 2.49c for GNU Autoconf 2.49d.
 #
 # Report bugs to <bug-autoconf@gnu.org>.
 #
@@ -79,7 +79,7 @@ cat >config.log <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by $as_me (GNU Autoconf 2.49d) 2.49d, executed with
+It was created by $as_me (GNU Autoconf 2.49d) 2.49c, executed with
  > $0 $@
 
 EOF
@@ -708,7 +708,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-configure (GNU Autoconf 2.49d) 2.49d
+configure (GNU Autoconf 2.49d) 2.49c
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000
 Free Software Foundation, Inc.
@@ -1159,12 +1159,18 @@ else
 echo "${ECHO_T}missing" >&6
 fi
 
+if test foo = found; then
+  foo=1
+else
+  foo=1
+fi
+
 # Initialize the test suite.
 AUTOTEST_PATH=..
 
 # Extract the first word of "expr", so it can be a program name with args.
 set dummy expr; ac_word=$2
-echo "$as_me:1167: checking for $ac_word" >&5
+echo "$as_me:1173: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_EXPR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1191,10 +1197,10 @@ fi
 EXPR=$ac_cv_path_EXPR
 
 if test -n "$EXPR"; then
-  echo "$as_me:1194: result: $EXPR" >&5
+  echo "$as_me:1200: result: $EXPR" >&5
 echo "${ECHO_T}$EXPR" >&6
 else
-  echo "$as_me:1197: result: no" >&5
+  echo "$as_me:1203: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1206,7 +1212,7 @@ for ac_prog in gm4 gnum4 m4
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1209: checking for $ac_word" >&5
+echo "$as_me:1215: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1233,10 +1239,10 @@ fi
 M4=$ac_cv_path_M4
 
 if test -n "$M4"; then
-  echo "$as_me:1236: result: $M4" >&5
+  echo "$as_me:1242: result: $M4" >&5
 echo "${ECHO_T}$M4" >&6
 else
-  echo "$as_me:1239: result: no" >&5
+  echo "$as_me:1245: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1244,7 +1250,7 @@ fi
 done
 test -n "$M4" || M4="m4"
 
-echo "$as_me:1247: checking whether m4 supports frozen files" >&5
+echo "$as_me:1253: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1256,10 +1262,10 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "$as_me:1259: result: $ac_cv_prog_gnu_m4" >&5
+echo "$as_me:1265: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { { echo "$as_me:1262: error: GNU m4 1.4 is required" >&5
+  { { echo "$as_me:1268: error: GNU m4 1.4 is required" >&5
 echo "$as_me: error: GNU m4 1.4 is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1271,7 +1277,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1274: checking for $ac_word" >&5
+echo "$as_me:1280: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1293,10 +1299,10 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1296: result: $AWK" >&5
+  echo "$as_me:1302: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1299: result: no" >&5
+  echo "$as_me:1305: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1304,25 +1310,25 @@ fi
 done
 
 # Generating man pages.
-echo "$as_me:1307: checking for working help2man" >&5
+echo "$as_me:1313: checking for working help2man" >&5
 echo $ECHO_N "checking for working help2man... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
 if (help2man --version) < /dev/null > /dev/null 2>&1; then
    HELP2MAN=help2man
-   echo "$as_me:1314: result: found" >&5
+   echo "$as_me:1320: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
    HELP2MAN="$SHELL $missing_dir/missing help2man"
-   echo "$as_me:1318: result: missing" >&5
+   echo "$as_me:1324: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
 
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1325: checking for $ac_word" >&5
+echo "$as_me:1331: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1350,17 +1356,17 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1353: result: $PERL" >&5
+  echo "$as_me:1359: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1356: result: no" >&5
+  echo "$as_me:1362: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" != no; then
   PERLSCRIPTS=autoscan
 else
-  { echo "$as_me:1363: WARNING: autoscan will not be built since perl is not found" >&5
+  { echo "$as_me:1369: WARNING: autoscan will not be built since perl is not found" >&5
 echo "$as_me: WARNING: autoscan will not be built since perl is not found" >&2;}
 fi
 
@@ -1376,7 +1382,7 @@ fi
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "$as_me:1379: checking for a BSD compatible install" >&5
+echo "$as_me:1385: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1425,7 +1431,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "$as_me:1428: result: $INSTALL" >&5
+echo "$as_me:1434: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -1539,7 +1545,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1542: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1548: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<\_ACEOF
 #! /bin/sh
@@ -1578,7 +1584,7 @@ if test -x conftest.file; then
 elif test -f conftest.file; then
   as_executable_p="test -f"
 else
-  { { echo "$as_me:1581: error: cannot check whether a file is executable on this system" >&5
+  { { echo "$as_me:1587: error: cannot check whether a file is executable on this system" >&5
 echo "$as_me: error: cannot check whether a file is executable on this system" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1625,7 +1631,7 @@ cat >&5 << EOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.49d) 2.49d, executed with
+This file was extended by $as_me (GNU Autoconf 2.49d) 2.49c, executed with
  > $0 $@
 on `(hostname || uname -n) 2>/dev/null | sed 1q`
 
@@ -1673,7 +1679,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-$CONFIG_STATUS generated by $as_me (Autoconf 2.49d).
+$CONFIG_STATUS generated by $as_me (Autoconf 2.49c).
 Configured on host $ac_hostname by
   `echo "$0 $ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`"
 srcdir=$srcdir
@@ -1713,7 +1719,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1716: error: ambiguous option: $1
+    { { echo "$as_me:1722: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1740,12 +1746,12 @@ Try \`$0 --help' for more information." >&2;}
   'tests/atconfig' ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:1743: error: unrecognized option: $1
+  -*) { { echo "$as_me:1749: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:1748: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:1754: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1958,7 +1964,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1961: creating $ac_file" >&5
+    { echo "$as_me:1967: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1976,7 +1982,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:1979: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1985: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1989,7 +1995,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1992: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1998: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
