`build_alias' and so on are not AC_SUBST'd. Reported by Bruno Haible. * acgeneral.m4 (AC_ARG_VAR): Move the AC_SUBST, from here...  (_AC_ARG_VAR_PRECIOUS): to here.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1787,6 +1787,9 @@ s,@PACKAGE_TARNAME@,$PACKAGE_TARNAME,;t t
 s,@PACKAGE_VERSION@,$PACKAGE_VERSION,;t t
 s,@PACKAGE_STRING@,$PACKAGE_STRING,;t t
 s,@PACKAGE_BUGREPORT@,$PACKAGE_BUGREPORT,;t t
+s,@build_alias@,$build_alias,;t t
+s,@host_alias@,$host_alias,;t t
+s,@target_alias@,$target_alias,;t t
 s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
@@ -1925,7 +1928,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1928: creating $ac_file" >&5
+    { echo "$as_me:1931: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1943,7 +1946,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1946: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1949: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1956,7 +1959,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1959: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1962: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
