Version 2.49c.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1676,9 +1676,8 @@ ac_cs_version="\\
 $CONFIG_STATUS generated by $as_me (Autoconf 2.49c).
 Configured on host $ac_hostname by
   `echo "$0 $ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`"
-
-ac_given_srcdir=$srcdir
-ac_given_INSTALL="$INSTALL"
+srcdir=$srcdir
+INSTALL="$INSTALL"
 EOF
 
 cat >>$CONFIG_STATUS <<\EOF
@@ -1714,7 +1713,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1717: error: ambiguous option: $1
+    { { echo "$as_me:1716: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1741,12 +1740,12 @@ Try \`$0 --help' for more information." >&2;}
   'tests/atconfig' ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:1744: error: unrecognized option: $1
+  -*) { { echo "$as_me:1743: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:1749: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:1748: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1902,7 +1901,7 @@ for ac_file in : $CONFIG_FILES; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  # Adjust a relative srcdir, top_srcdir, and INSTALL for subdirectories.
+  # Compute @srcdir@, @top_srcdir@, and @INSTALL@ for subdirectories.
   ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
          X"$ac_file" : 'X\(//\)[^/]' \| \
          X"$ac_file" : 'X\(//\)$' \| \
@@ -1938,25 +1937,28 @@ done; }
     ac_dir_suffix= ac_dots=
   fi
 
-  case $ac_given_srcdir in
-  .)  srcdir=.
-      if test -z "$ac_dots"; then top_srcdir=.
-      else top_srcdir=`echo $ac_dots | sed 's,/$,,'`; fi ;;
+  case $srcdir in
+  .)  ac_srcdir=.
+      if test -z "$ac_dots"; then
+         ac_top_srcdir=.
+      else
+         ac_top_srcdir=`echo $ac_dots | sed 's,/$,,'`
+      fi ;;
   [\\/]* | ?:[\\/]* )
-      srcdir=$ac_given_srcdir$ac_dir_suffix;
-      top_srcdir=$ac_given_srcdir ;;
+      ac_srcdir=$srcdir$ac_dir_suffix;
+      ac_top_srcdir=$srcdir ;;
   *) # Relative path.
-    srcdir=$ac_dots$ac_given_srcdir$ac_dir_suffix
-    top_srcdir=$ac_dots$ac_given_srcdir ;;
+    ac_srcdir=$ac_dots$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_dots$srcdir ;;
   esac
 
-  case $ac_given_INSTALL in
-  [\\/$]* | ?:[\\/]* ) INSTALL=$ac_given_INSTALL ;;
-  *) INSTALL=$ac_dots$ac_given_INSTALL ;;
+  case $INSTALL in
+  [\\/$]* | ?:[\\/]* ) ac_INSTALL=$INSTALL ;;
+  *) ac_INSTALL=$ac_dots$INSTALL ;;
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1959: creating $ac_file" >&5
+    { echo "$as_me:1961: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1974,7 +1976,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:1977: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1979: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1982,12 +1984,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
          if test -f "$f"; then
            # Build tree
            echo $f
-         elif test -f "$ac_given_srcdir/$f"; then
+         elif test -f "$srcdir/$f"; then
            # Source tree
-           echo $ac_given_srcdir/$f
+           echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1990: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1992: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2002,9 +2004,9 @@ cat >>$CONFIG_STATUS <<\EOF
 :t
 /@[a-zA-Z_][a-zA-Z_0-9]*@/!b
 s,@configure_input@,$configure_input,;t t
-s,@srcdir@,$srcdir,;t t
-s,@top_srcdir@,$top_srcdir,;t t
-s,@INSTALL@,$INSTALL,;t t
+s,@srcdir@,$ac_srcdir,;t t
+s,@top_srcdir@,$ac_top_srcdir,;t t
+s,@INSTALL@,$ac_INSTALL,;t t
 " $ac_file_inputs | (eval "$ac_sed_cmds") >$tmp/out
   rm -f $tmp/stdin
   if test x"$ac_file" != x-; then
