Version 2.52d.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52c for GNU Autoconf 2.52c.
+# Generated by Autoconf 2.52c for GNU Autoconf 2.52d.
 #
 # Report bugs to <bug-autoconf@gnu.org>.
 #
@@ -153,8 +153,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52c'
-PACKAGE_STRING='GNU Autoconf 2.52c'
+PACKAGE_VERSION='2.52d'
+PACKAGE_STRING='GNU Autoconf 2.52d'
 PACKAGE_BUGREPORT='bug-autoconf@gnu.org'
 
 ac_prev=
@@ -551,7 +551,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<_ACEOF
-\`configure' configures GNU Autoconf 2.52c to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52d to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -613,7 +613,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52c:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52d:";;
    esac
   cat <<\_ACEOF
 
@@ -677,7 +677,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\_ACEOF
-GNU Autoconf configure 2.52c
+GNU Autoconf configure 2.52d
 generated by GNU Autoconf 2.52c
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -692,7 +692,7 @@ cat >&5 <<_ACEOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52c, which was
+It was created by GNU Autoconf $as_me 2.52d, which was
 generated by GNU Autoconf 2.52c.  Invocation command line was
 
   $ $0 $@
@@ -1200,7 +1200,7 @@ fi
 
 # Define the identity of the package.
 PACKAGE=autoconf
-VERSION=2.52c
+VERSION=2.52d
 
 cat >>confdefs.h <<_ACEOF
 #define PACKAGE "$PACKAGE"
@@ -1652,13 +1652,15 @@ exec 6>&1
 # report actual input values of CONFIG_FILES etc. instead of their
 # values after options handling.  Logging --version etc. is OK.
 exec 5>>config.log
+{
+  echo
+  sed 'h;s/./-/g;s/^.../## /;s/...$/ ##/;p;x;p;x' <<_ASBOX
+## Running \$as_me. ##
+_ASBOX
+} >&5
 cat >&5 <<_CSEOF
 
-`sed 'h;s/./-/g;s/^.../## /;s/...$/ ##/;p;x;p;x' <<_ASBOX
-## Running \$as_me. ##
-_ASBOX`
-
-This file was extended by GNU Autoconf $as_me 2.52c, which was
+This file was extended by GNU Autoconf $as_me 2.52d, which was
 generated by GNU Autoconf 2.52c.  Invocation command line was
 
   CONFIG_FILES    = $CONFIG_FILES
@@ -1666,9 +1668,10 @@ generated by GNU Autoconf 2.52c.  Invocation command line was
   CONFIG_LINKS    = $CONFIG_LINKS
   CONFIG_COMMANDS = $CONFIG_COMMANDS
   $ $@
-on `(hostname || uname -n) 2>/dev/null | sed 1q`
 
 _CSEOF
+echo "on `(hostname || uname -n) 2>/dev/null | sed 1q`" >&5
+echo >&5
 _ACEOF
 
 # Files that config.status was made for.
@@ -1714,7 +1717,7 @@ _ACEOF
 
 cat >>$CONFIG_STATUS <<_ACEOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52c
+GNU Autoconf config.status 2.52d
 configured by $0, generated by GNU Autoconf 2.52c,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -1759,7 +1762,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1762: error: ambiguous option: $1
+    { { echo "$as_me:1765: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1778,7 +1781,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1781: error: unrecognized option: $1
+  -*) { { echo "$as_me:1784: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1829,7 +1832,7 @@ do
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_COMMANDS="$CONFIG_COMMANDS tests/atconfig" ;;
-  *) { { echo "$as_me:1832: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1835: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2017,7 +2020,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:2020: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:2023: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -2054,7 +2057,7 @@ esac
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2057: creating $ac_file" >&5
+    { echo "$as_me:2060: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2072,7 +2075,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2075: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2078: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2085,7 +2088,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2088: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2091: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2157,7 +2160,7 @@ case $srcdir in
     ac_top_srcdir=$ac_top_builddir$srcdir ;;
 esac
 
-  { echo "$as_me:2160: executing $ac_dest commands" >&5
+  { echo "$as_me:2163: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
     tests/atconfig ) cat >tests/atconfig <<ATEOF
