Huh!?!?!  There are still some user EOF tags used, which prevents their use in AC_CONFIG_COMMANDS for instance... * lib/autoconf/general.m4, lib/autoconf/specific.m4, * lib/autotest/general.m4: Rename the EOF tags as `_ACEOF', `_CSEOF', or `_ATEOF', as appropriate. * lib/m4sugar/Makefile.am, lib/autoconf/Makefile.am, * lib/autotest/Makefile.am (check-local): Enforce this constraint.

diff --git a/lib/autoconf/Makefile.am b/lib/autoconf/Makefile.am
--- a/lib/autoconf/Makefile.am
+++ b/lib/autoconf/Makefile.am
@@ -54,6 +54,22 @@ ETAGS_ARGS = --lang=none \
 
 
 
+## -------- ##
+## Checks.  ##
+## -------- ##
+
+check-local:
+	if (cd $(srcdir) && \
+	    egrep '^_?EOF' $(distautoconflib_DATA)) >eof.log; then \
+	  echo "ERROR: user EOF tags were used:" >&2; \
+	  sed "s,^,$*.m4: ," <eof.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f eof.log; \
+	fi
+
+
 ## ------------------ ##
 ## The frozen files.  ##
 ## ------------------ ##
@@ -99,6 +115,7 @@ M4_INCLUDES =  --include $(srcdir) \
 	else \
 	  rm -f freeze.log; \
 	fi
+
 
 # Some day we should explain to Automake how to use autom4te to compute
 # the dependencies...
diff --git a/lib/autoconf/Makefile.in b/lib/autoconf/Makefile.in
--- a/lib/autoconf/Makefile.in
+++ b/lib/autoconf/Makefile.in
@@ -204,6 +204,7 @@ info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-local
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -261,11 +262,12 @@ maintainer-clean: maintainer-clean-am
 .PHONY: uninstall-distautoconflibDATA install-distautoconflibDATA \
 uninstall-nodistautoconflibDATA install-nodistautoconflibDATA tags \
 mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
-distdir info-am info dvi-am dvi check check-am installcheck-am \
-installcheck install-exec-am install-exec install-data-am install-data \
-install-am install uninstall-am uninstall all-redirect all-am all \
-installdirs mostlyclean-generic distclean-generic clean-generic \
-maintainer-clean-generic clean mostlyclean distclean maintainer-clean
+distdir info-am info dvi-am dvi check-local check check-am \
+installcheck-am installcheck install-exec-am install-exec \
+install-data-am install-data install-am install uninstall-am uninstall \
+all-redirect all-am all installdirs mostlyclean-generic \
+distclean-generic clean-generic maintainer-clean-generic clean \
+mostlyclean distclean maintainer-clean
 
 
 # - version.m4 needs to be updated only once, since it depends on
@@ -277,6 +279,17 @@ maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 $(srcdir)/version.m4: $(srcdir)/version.in $(top_srcdir)/configure.ac
 	sed 's,@VERSION\@,$(VERSION),g' $(srcdir)/version.in >version.tm4
 	mv version.tm4 $(srcdir)/version.m4
+
+check-local:
+	if (cd $(srcdir) && \
+	    egrep '^_?EOF' $(distautoconflib_DATA)) >eof.log; then \
+	  echo "ERROR: user EOF tags were used:" >&2; \
+	  sed "s,^,$*.m4: ," <eof.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f eof.log; \
+	fi
 
 # When processing the file with diversion disabled, there must be no
 # output but comments and empty lines.
diff --git a/lib/autotest/Makefile.in b/lib/autotest/Makefile.in
--- a/lib/autotest/Makefile.in
+++ b/lib/autotest/Makefile.in
@@ -170,6 +170,7 @@ info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-local
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -222,12 +223,24 @@ maintainer-clean: maintainer-clean-am
 
 .PHONY: uninstall-autotestlibDATA install-autotestlibDATA tags \
 mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
-distdir info-am info dvi-am dvi check check-am installcheck-am \
-installcheck install-exec-am install-exec install-data-am install-data \
-install-am install uninstall-am uninstall all-redirect all-am all \
-installdirs mostlyclean-generic distclean-generic clean-generic \
-maintainer-clean-generic clean mostlyclean distclean maintainer-clean
+distdir info-am info dvi-am dvi check-local check check-am \
+installcheck-am installcheck install-exec-am install-exec \
+install-data-am install-data install-am install uninstall-am uninstall \
+all-redirect all-am all installdirs mostlyclean-generic \
+distclean-generic clean-generic maintainer-clean-generic clean \
+mostlyclean distclean maintainer-clean
 
+
+check-local:
+	if (cd $(srcdir) && \
+	    egrep '^_?EOF' $(autotestlib_DATA)) >eof.log; then \
+	  echo "ERROR: user EOF tags were used:" >&2; \
+	  sed "s,^,$*.m4: ," <eof.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f eof.log; \
+	fi
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
diff --git a/lib/m4sugar/Makefile.am b/lib/m4sugar/Makefile.am
--- a/lib/m4sugar/Makefile.am
+++ b/lib/m4sugar/Makefile.am
@@ -15,3 +15,19 @@ TAGS_FILES = $(m4sugarlib_DATA)
 
 ETAGS_ARGS = --lang=none \
   --regex='/\(A[CU]_DEFUN\|m4_\(defun\|define\)\|define\)(\[\([^]]*\)\]/\3/'
+
+
+## -------- ##
+## Checks.  ##
+## -------- ##
+
+check-local:
+	if (cd $(srcdir) && \
+	    egrep '^_?EOF' $(m4sugarlib_DATA)) >eof.log; then \
+	  echo "ERROR: user EOF tags were used:" >&2; \
+	  sed "s,^,$*.m4: ," <eof.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f eof.log; \
+	fi
