* lib/autoconf/general.m4 (AC_CACHE_SAVE): Don't use cmp. Fixes the `AC_ARG_VAR' test failures. * lib/autoconf/status.m4 (_AC_OUTPUT_FILES): Don't use cmp. * lib/freeze.mk (check-forbidden-patterns): New. * lib/autoconf/Makefile.am, lib/autotest/Makefile.am * lib/m4sugar/Makefile.am (check-local): Use it to catch `cmp'. * doc/autoconf.texi (Limitations of Usual Tools): HP-UX' cmp and /dev/null. Reported months ago by H. Merijn Brand.

diff --git a/lib/autoconf/Makefile.in b/lib/autoconf/Makefile.in
--- a/lib/autoconf/Makefile.in
+++ b/lib/autoconf/Makefile.in
@@ -106,6 +106,8 @@ CLEANFILES = $(nodist_autoconflib_DATA)
 TAGS_FILES = $(dist_autoconflib_DATA)
 
 ETAGS_ARGS = $(ETAGS_FOR_AUTOCONF)
+forbidden_patterns = -e '^_*EOF' -e ' cmp '
+forbidden_patterns_files = $(dist_autoconflib_DATA)
 
 SUFFIXES = .m4 .m4f
 
@@ -292,11 +294,13 @@ top_distdir = ../..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
-	$(mkinstalldirs) $(distdir)/$(srcdir)/..
+	$(mkinstalldirs) $(distdir)/./..
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
+	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
 	  case $$file in \
 	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
+	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
 	  esac; \
 	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
 	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
@@ -409,16 +413,7 @@ uninstall-am: uninstall-dist_autoconflibDATA uninstall-info-am \
 	uninstall-nodist_autoconflibDATA
 
 
-check-local:
-	if (cd $(srcdir) && \
-	    grep '^_*EOF' $(dist_autoconflib_DATA)) >eof.log; then \
-	  echo "ERROR: user EOF tags were used:" >&2; \
-	  sed "s,^,$*.m4: ," <eof.log >&2; \
-	  echo >&2; \
-	  exit 1; \
-	else \
-	  rm -f eof.log; \
-	fi
+check-local: check-forbidden-patterns
 
 autoconf.m4f: $(autoconf_m4f_dependencies)
 $(MY_AUTOM4TE):
@@ -441,6 +436,18 @@ $(AUTOM4TE_CFG):
 # For parallel builds.
 $(build_libdir)/m4sugar/version.m4:
 	cd $(build_libdir)/m4sugar && $(MAKE) $(AM_MAKEFLAGS) version.m4
+
+check-forbidden-patterns:
+	if (cd $(srcdir) && \
+	    grep $(forbidden_patterns) $(forbidden_patterns_files)) \
+	    >forbidden.log; then \
+	  echo "ERROR: forbidden patterns were found:" >&2; \
+	  sed "s,^,$*.m4: ," <forbidden.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f forbidden.log; \
+	fi
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
diff --git a/lib/m4sugar/Makefile.in b/lib/m4sugar/Makefile.in
--- a/lib/m4sugar/Makefile.in
+++ b/lib/m4sugar/Makefile.in
@@ -99,6 +99,8 @@ CLEANFILES = $(nodist_m4sugarlib_DATA)
 TAGS_FILES = $(dist_m4sugarlib_DATA)
 
 ETAGS_ARGS = $(ETAGS_FOR_AUTOCONF)
+forbidden_patterns = -e '^_*EOF' -e ' cmp '
+forbidden_patterns_files = $(dist_m4sugarlib_DATA)
 
 SUFFIXES = .m4 .m4f
 
@@ -285,11 +287,13 @@ top_distdir = ../..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
-	$(mkinstalldirs) $(distdir)/$(srcdir)/..
+	$(mkinstalldirs) $(distdir)/./..
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
+	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
 	  case $$file in \
 	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
+	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
 	  esac; \
 	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
 	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
@@ -416,16 +420,7 @@ version.m4: $(top_srcdir)/configure.ac
 	  echo 'm4_define([m4_PACKAGE_BUGREPORT], [@PACKAGE_BUGREPORT@])'; \
 	} >version.m4
 
-check-local:
-	if (cd $(srcdir) && \
-	    grep '^_*EOF' $(dist_m4sugarlib_DATA)) >eof.log; then \
-	  echo "ERROR: user EOF tags were used:" >&2; \
-	  sed "s,^,$*.m4: ," <eof.log >&2; \
-	  echo >&2; \
-	  exit 1; \
-	else \
-	  rm -f eof.log; \
-	fi
+check-local: check-forbidden-patterns
 
 m4sugar.m4f: $(m4sugar_m4f_dependencies)
 m4sh.m4f: $(m4sh_m4f_dependencies)
@@ -449,6 +444,18 @@ $(AUTOM4TE_CFG):
 # For parallel builds.
 $(build_libdir)/m4sugar/version.m4:
 	cd $(build_libdir)/m4sugar && $(MAKE) $(AM_MAKEFLAGS) version.m4
+
+check-forbidden-patterns:
+	if (cd $(srcdir) && \
+	    grep $(forbidden_patterns) $(forbidden_patterns_files)) \
+	    >forbidden.log; then \
+	  echo "ERROR: forbidden patterns were found:" >&2; \
+	  sed "s,^,$*.m4: ," <forbidden.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f forbidden.log; \
+	fi
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -267,11 +267,13 @@ top_distdir = ..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
-	$(mkinstalldirs) $(distdir)/$(srcdir)/../lib
+	$(mkinstalldirs) $(distdir)/./../lib
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
+	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
 	  case $$file in \
 	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
+	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
 	  esac; \
 	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
 	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
@@ -400,6 +402,18 @@ $(AUTOM4TE_CFG):
 # For parallel builds.
 $(build_libdir)/m4sugar/version.m4:
 	cd $(build_libdir)/m4sugar && $(MAKE) $(AM_MAKEFLAGS) version.m4
+
+check-forbidden-patterns:
+	if (cd $(srcdir) && \
+	    grep $(forbidden_patterns) $(forbidden_patterns_files)) \
+	    >forbidden.log; then \
+	  echo "ERROR: forbidden patterns were found:" >&2; \
+	  sed "s,^,$*.m4: ," <forbidden.log >&2; \
+	  echo >&2; \
+	  exit 1; \
+	else \
+	  rm -f forbidden.log; \
+	fi
 
 # Import the dependencies on Autotest and M4sh.
 
